=begin
#EdiFabric API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.4

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::EdiFabricWebApiModelsGenerateEdifactInterchange
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'EdiFabricWebApiModelsGenerateEdifactInterchange' do
  before do
    # run before each test
    @instance = SwaggerClient::EdiFabricWebApiModelsGenerateEdifactInterchange.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EdiFabricWebApiModelsGenerateEdifactInterchange' do
    it 'should create an instance of EdiFabricWebApiModelsGenerateEdifactInterchange' do
      expect(@instance).to be_instance_of(SwaggerClient::EdiFabricWebApiModelsGenerateEdifactInterchange)
    end
  end
  describe 'test attribute "settings"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "unb"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "groups"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "unz_trailers"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "errors"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
