/* 
 * EdiFabric API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EdiFabricCoreModelEdiEdifactS005
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EdiFabricCoreModelEdiEdifactS005Tests
    {
        // TODO uncomment below to declare an instance variable for EdiFabricCoreModelEdiEdifactS005
        //private EdiFabricCoreModelEdiEdifactS005 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EdiFabricCoreModelEdiEdifactS005
            //instance = new EdiFabricCoreModelEdiEdifactS005();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EdiFabricCoreModelEdiEdifactS005
        /// </summary>
        [Test]
        public void EdiFabricCoreModelEdiEdifactS005InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EdiFabricCoreModelEdiEdifactS005
            //Assert.IsInstanceOfType<EdiFabricCoreModelEdiEdifactS005> (instance, "variable 'instance' is a EdiFabricCoreModelEdiEdifactS005");
        }


        /// <summary>
        /// Test the property 'RecipientReferencePassword1'
        /// </summary>
        [Test]
        public void RecipientReferencePassword1Test()
        {
            // TODO unit test for the property 'RecipientReferencePassword1'
        }
        /// <summary>
        /// Test the property 'RecipientReferencePasswordQualifier2'
        /// </summary>
        [Test]
        public void RecipientReferencePasswordQualifier2Test()
        {
            // TODO unit test for the property 'RecipientReferencePasswordQualifier2'
        }

    }

}
