/* 
 * EdiFabric API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EdiFabricCoreModelEdiErrorContextsSegmentErrorContext
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EdiFabricCoreModelEdiErrorContextsSegmentErrorContextTests
    {
        // TODO uncomment below to declare an instance variable for EdiFabricCoreModelEdiErrorContextsSegmentErrorContext
        //private EdiFabricCoreModelEdiErrorContextsSegmentErrorContext instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EdiFabricCoreModelEdiErrorContextsSegmentErrorContext
            //instance = new EdiFabricCoreModelEdiErrorContextsSegmentErrorContext();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EdiFabricCoreModelEdiErrorContextsSegmentErrorContext
        /// </summary>
        [Test]
        public void EdiFabricCoreModelEdiErrorContextsSegmentErrorContextInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EdiFabricCoreModelEdiErrorContextsSegmentErrorContext
            //Assert.IsInstanceOfType<EdiFabricCoreModelEdiErrorContextsSegmentErrorContext> (instance, "variable 'instance' is a EdiFabricCoreModelEdiErrorContextsSegmentErrorContext");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Codes'
        /// </summary>
        [Test]
        public void CodesTest()
        {
            // TODO unit test for the property 'Codes'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Test]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
