/* 
 * EdiFabric API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EdiFabricCoreModelEdiEdifactS008
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EdiFabricCoreModelEdiEdifactS008Tests
    {
        // TODO uncomment below to declare an instance variable for EdiFabricCoreModelEdiEdifactS008
        //private EdiFabricCoreModelEdiEdifactS008 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EdiFabricCoreModelEdiEdifactS008
            //instance = new EdiFabricCoreModelEdiEdifactS008();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EdiFabricCoreModelEdiEdifactS008
        /// </summary>
        [Test]
        public void EdiFabricCoreModelEdiEdifactS008InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EdiFabricCoreModelEdiEdifactS008
            //Assert.IsInstanceOfType<EdiFabricCoreModelEdiEdifactS008> (instance, "variable 'instance' is a EdiFabricCoreModelEdiEdifactS008");
        }


        /// <summary>
        /// Test the property 'MessageVersionNumber1'
        /// </summary>
        [Test]
        public void MessageVersionNumber1Test()
        {
            // TODO unit test for the property 'MessageVersionNumber1'
        }
        /// <summary>
        /// Test the property 'MessageReleaseNumber2'
        /// </summary>
        [Test]
        public void MessageReleaseNumber2Test()
        {
            // TODO unit test for the property 'MessageReleaseNumber2'
        }
        /// <summary>
        /// Test the property 'AssociationAssignedCode3'
        /// </summary>
        [Test]
        public void AssociationAssignedCode3Test()
        {
            // TODO unit test for the property 'AssociationAssignedCode3'
        }

    }

}
