/* 
 * EdiFabric API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EdiFabricWebApiModelsGenerateEdifactGroup
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EdiFabricWebApiModelsGenerateEdifactGroupTests
    {
        // TODO uncomment below to declare an instance variable for EdiFabricWebApiModelsGenerateEdifactGroup
        //private EdiFabricWebApiModelsGenerateEdifactGroup instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EdiFabricWebApiModelsGenerateEdifactGroup
            //instance = new EdiFabricWebApiModelsGenerateEdifactGroup();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EdiFabricWebApiModelsGenerateEdifactGroup
        /// </summary>
        [Test]
        public void EdiFabricWebApiModelsGenerateEdifactGroupInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EdiFabricWebApiModelsGenerateEdifactGroup
            //Assert.IsInstanceOfType<EdiFabricWebApiModelsGenerateEdifactGroup> (instance, "variable 'instance' is a EdiFabricWebApiModelsGenerateEdifactGroup");
        }


        /// <summary>
        /// Test the property 'Settings'
        /// </summary>
        [Test]
        public void SettingsTest()
        {
            // TODO unit test for the property 'Settings'
        }
        /// <summary>
        /// Test the property 'Ung'
        /// </summary>
        [Test]
        public void UngTest()
        {
            // TODO unit test for the property 'Ung'
        }
        /// <summary>
        /// Test the property 'UneTrailers'
        /// </summary>
        [Test]
        public void UneTrailersTest()
        {
            // TODO unit test for the property 'UneTrailers'
        }
        /// <summary>
        /// Test the property 'Transactions'
        /// </summary>
        [Test]
        public void TransactionsTest()
        {
            // TODO unit test for the property 'Transactions'
        }

    }

}
