/* 
 * EdiFabric API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EdiFabricWebApiModelsX12Interchange
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EdiFabricWebApiModelsX12InterchangeTests
    {
        // TODO uncomment below to declare an instance variable for EdiFabricWebApiModelsX12Interchange
        //private EdiFabricWebApiModelsX12Interchange instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EdiFabricWebApiModelsX12Interchange
            //instance = new EdiFabricWebApiModelsX12Interchange();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EdiFabricWebApiModelsX12Interchange
        /// </summary>
        [Test]
        public void EdiFabricWebApiModelsX12InterchangeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EdiFabricWebApiModelsX12Interchange
            //Assert.IsInstanceOfType<EdiFabricWebApiModelsX12Interchange> (instance, "variable 'instance' is a EdiFabricWebApiModelsX12Interchange");
        }


        /// <summary>
        /// Test the property 'Isa'
        /// </summary>
        [Test]
        public void IsaTest()
        {
            // TODO unit test for the property 'Isa'
        }
        /// <summary>
        /// Test the property 'Groups'
        /// </summary>
        [Test]
        public void GroupsTest()
        {
            // TODO unit test for the property 'Groups'
        }
        /// <summary>
        /// Test the property 'IeaTrailers'
        /// </summary>
        [Test]
        public void IeaTrailersTest()
        {
            // TODO unit test for the property 'IeaTrailers'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Test]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }

    }

}
