/* 
 * EdiFabric API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EdiFabricCoreModelEdiErrorContextsMessageErrorContext
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EdiFabricCoreModelEdiErrorContextsMessageErrorContextTests
    {
        // TODO uncomment below to declare an instance variable for EdiFabricCoreModelEdiErrorContextsMessageErrorContext
        //private EdiFabricCoreModelEdiErrorContextsMessageErrorContext instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EdiFabricCoreModelEdiErrorContextsMessageErrorContext
            //instance = new EdiFabricCoreModelEdiErrorContextsMessageErrorContext();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EdiFabricCoreModelEdiErrorContextsMessageErrorContext
        /// </summary>
        [Test]
        public void EdiFabricCoreModelEdiErrorContextsMessageErrorContextInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EdiFabricCoreModelEdiErrorContextsMessageErrorContext
            //Assert.IsInstanceOfType<EdiFabricCoreModelEdiErrorContextsMessageErrorContext> (instance, "variable 'instance' is a EdiFabricCoreModelEdiErrorContextsMessageErrorContext");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ControlNumber'
        /// </summary>
        [Test]
        public void ControlNumberTest()
        {
            // TODO unit test for the property 'ControlNumber'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'Codes'
        /// </summary>
        [Test]
        public void CodesTest()
        {
            // TODO unit test for the property 'Codes'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Test]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
        /// <summary>
        /// Test the property 'HasErrors'
        /// </summary>
        [Test]
        public void HasErrorsTest()
        {
            // TODO unit test for the property 'HasErrors'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
