# coding: utf-8

"""
    EdiFabric API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.edi_fabric_core_model_edi_edifact_s003 import EdiFabricCoreModelEdiEdifactS003  # noqa: E501
from swagger_client.rest import ApiException


class TestEdiFabricCoreModelEdiEdifactS003(unittest.TestCase):
    """EdiFabricCoreModelEdiEdifactS003 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEdiFabricCoreModelEdiEdifactS003(self):
        """Test EdiFabricCoreModelEdiEdifactS003"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.edi_fabric_core_model_edi_edifact_s003.EdiFabricCoreModelEdiEdifactS003()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
