# coding: utf-8

"""
    EdiFabric API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.translate_api import TranslateApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTranslateApi(unittest.TestCase):
    """TranslateApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.translate_api.TranslateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_translate_edifact(self):
        """Test case for translate_edifact

        """
        pass

    def test_translate_x12(self):
        """Test case for translate_x12

        """
        pass


if __name__ == '__main__':
    unittest.main()
