# coding: utf-8

"""
    EdiFabric API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.edi_fabric_web_api_models_generate_x12_transactions import EdiFabricWebApiModelsGenerateX12Transactions  # noqa: E501
from swagger_client.rest import ApiException


class TestEdiFabricWebApiModelsGenerateX12Transactions(unittest.TestCase):
    """EdiFabricWebApiModelsGenerateX12Transactions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEdiFabricWebApiModelsGenerateX12Transactions(self):
        """Test EdiFabricWebApiModelsGenerateX12Transactions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.edi_fabric_web_api_models_generate_x12_transactions.EdiFabricWebApiModelsGenerateX12Transactions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
