#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* EdiFabric API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGEdiFabricCoreModelEdiEdiMessage.h"
#import "SWGEdiFabricCoreModelEdiEdifactUNE.h"
#import "SWGEdiFabricCoreModelEdiEdifactUNG.h"
@protocol SWGEdiFabricCoreModelEdiEdiMessage;
@class SWGEdiFabricCoreModelEdiEdiMessage;
@protocol SWGEdiFabricCoreModelEdiEdifactUNE;
@class SWGEdiFabricCoreModelEdiEdifactUNE;
@protocol SWGEdiFabricCoreModelEdiEdifactUNG;
@class SWGEdiFabricCoreModelEdiEdifactUNG;



@protocol SWGEdiFabricWebApiModelsEdifactGroup
@end

@interface SWGEdiFabricWebApiModelsEdifactGroup : SWGObject


@property(nonatomic) SWGEdiFabricCoreModelEdiEdifactUNG* ung;

@property(nonatomic) NSArray<SWGEdiFabricCoreModelEdiEdifactUNE>* uneTrailers;

@property(nonatomic) NSArray<SWGEdiFabricCoreModelEdiEdiMessage>* transactions;

@end
