#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* EdiFabric API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGEdiFabricCoreModelEdiEdifactS001.h"
#import "SWGEdiFabricCoreModelEdiEdifactS002.h"
#import "SWGEdiFabricCoreModelEdiEdifactS003.h"
#import "SWGEdiFabricCoreModelEdiEdifactS004.h"
#import "SWGEdiFabricCoreModelEdiEdifactS005.h"
@protocol SWGEdiFabricCoreModelEdiEdifactS001;
@class SWGEdiFabricCoreModelEdiEdifactS001;
@protocol SWGEdiFabricCoreModelEdiEdifactS002;
@class SWGEdiFabricCoreModelEdiEdifactS002;
@protocol SWGEdiFabricCoreModelEdiEdifactS003;
@class SWGEdiFabricCoreModelEdiEdifactS003;
@protocol SWGEdiFabricCoreModelEdiEdifactS004;
@class SWGEdiFabricCoreModelEdiEdifactS004;
@protocol SWGEdiFabricCoreModelEdiEdifactS005;
@class SWGEdiFabricCoreModelEdiEdifactS005;



@protocol SWGEdiFabricCoreModelEdiEdifactUNB
@end

@interface SWGEdiFabricCoreModelEdiEdifactUNB : SWGObject


@property(nonatomic) SWGEdiFabricCoreModelEdiEdifactS001* syntaxidentifieR1;

@property(nonatomic) SWGEdiFabricCoreModelEdiEdifactS002* interchangesendeR2;

@property(nonatomic) SWGEdiFabricCoreModelEdiEdifactS003* interchangerecipienT3;

@property(nonatomic) SWGEdiFabricCoreModelEdiEdifactS004* dateandtimeofpreparatioN4;

@property(nonatomic) NSString* interchangeControlReference5;

@property(nonatomic) SWGEdiFabricCoreModelEdiEdifactS005* recipientsreferencepassworddetailS6;

@property(nonatomic) NSString* applicationReference7;

@property(nonatomic) NSString* processingPriorityCode8;

@property(nonatomic) NSString* acknowledgementRequest9;

@property(nonatomic) NSString* interchangeAgreementIdentifier10;

@property(nonatomic) NSString* testIndicator11;

@end
