#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* EdiFabric API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGEdiFabricCoreModelEdiEdifactS002
@end

@interface SWGEdiFabricCoreModelEdiEdifactS002 : SWGObject


@property(nonatomic) NSString* interchangeSenderIdentification1;

@property(nonatomic) NSString* identificationCodeQualifier2;

@property(nonatomic) NSString* interchangeSenderInternalIdentification3;

@property(nonatomic) NSString* interchangeSenderInternalSubIdentification4;

@end
