/* 
 * EdiFabric API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAcknowledgeApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ediFile">EDI file to translate</param>
        /// <param name="readMode"> (optional, default to read_small)</param>
        /// <param name="accept"> (optional, default to application/json)</param>
        /// <param name="charSet"> (optional, default to utf-8)</param>
        /// <param name="continueOnError"> (optional, default to true)</param>
        /// <param name="skipTrailerValidation"> (optional, default to false)</param>
        /// <param name="decimalPoint"> (optional, default to .)</param>
        /// <param name="syntaxSet"> (optional)</param>
        /// <param name="transactionDuplicate"> (optional, default to false)</param>
        /// <param name="groupDuplicate"> (optional, default to false)</param>
        /// <param name="technicalAck"> (optional, default to default)</param>
        /// <param name="generateForValidTransactions"> (optional, default to false)</param>
        /// <param name="allowPartial"> (optional, default to false)</param>
        /// <param name="transactionControlNumber"> (optional, default to 1)</param>
        /// <param name="eancomSyntax"> (optional)</param>
        /// <param name="includeTransactions"> (optional, default to false)</param>
        /// <returns>List&lt;EdiFabricWebApiModelsEdifactAcknowledgment&gt;</returns>
        List<EdiFabricWebApiModelsEdifactAcknowledgment> AcknowledgeEdifact (System.IO.Stream ediFile, string readMode = null, string accept = null, string charSet = null, bool? continueOnError = null, bool? skipTrailerValidation = null, string decimalPoint = null, string syntaxSet = null, bool? transactionDuplicate = null, bool? groupDuplicate = null, string technicalAck = null, bool? generateForValidTransactions = null, bool? allowPartial = null, int? transactionControlNumber = null, string eancomSyntax = null, bool? includeTransactions = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ediFile">EDI file to translate</param>
        /// <param name="readMode"> (optional, default to read_small)</param>
        /// <param name="accept"> (optional, default to application/json)</param>
        /// <param name="charSet"> (optional, default to utf-8)</param>
        /// <param name="continueOnError"> (optional, default to true)</param>
        /// <param name="skipTrailerValidation"> (optional, default to false)</param>
        /// <param name="decimalPoint"> (optional, default to .)</param>
        /// <param name="syntaxSet"> (optional)</param>
        /// <param name="transactionDuplicate"> (optional, default to false)</param>
        /// <param name="groupDuplicate"> (optional, default to false)</param>
        /// <param name="technicalAck"> (optional, default to default)</param>
        /// <param name="generateForValidTransactions"> (optional, default to false)</param>
        /// <param name="allowPartial"> (optional, default to false)</param>
        /// <param name="transactionControlNumber"> (optional, default to 1)</param>
        /// <param name="eancomSyntax"> (optional)</param>
        /// <param name="includeTransactions"> (optional, default to false)</param>
        /// <returns>ApiResponse of List&lt;EdiFabricWebApiModelsEdifactAcknowledgment&gt;</returns>
        ApiResponse<List<EdiFabricWebApiModelsEdifactAcknowledgment>> AcknowledgeEdifactWithHttpInfo (System.IO.Stream ediFile, string readMode = null, string accept = null, string charSet = null, bool? continueOnError = null, bool? skipTrailerValidation = null, string decimalPoint = null, string syntaxSet = null, bool? transactionDuplicate = null, bool? groupDuplicate = null, string technicalAck = null, bool? generateForValidTransactions = null, bool? allowPartial = null, int? transactionControlNumber = null, string eancomSyntax = null, bool? includeTransactions = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ediFile">EDI file to translate</param>
        /// <param name="readMode"> (optional, default to read_small)</param>
        /// <param name="accept"> (optional, default to application/json)</param>
        /// <param name="charSet"> (optional, default to utf-8)</param>
        /// <param name="continueOnError"> (optional, default to true)</param>
        /// <param name="skipTrailerValidation"> (optional, default to false)</param>
        /// <param name="syntaxSet"> (optional)</param>
        /// <param name="transactionDuplicate"> (optional, default to false)</param>
        /// <param name="groupDuplicate"> (optional, default to false)</param>
        /// <param name="technicalAck"> (optional, default to default)</param>
        /// <param name="generateForValidTransactions"> (optional, default to false)</param>
        /// <param name="allowPartial"> (optional, default to false)</param>
        /// <param name="transactionControlNumber"> (optional, default to 1)</param>
        /// <param name="ak901"> (optional, default to e)</param>
        /// <param name="ackVersion"> (optional, default to 4010_997)</param>
        /// <param name="includeTransactions"> (optional, default to false)</param>
        /// <returns>List&lt;EdiFabricWebApiModelsX12Acknowledgment&gt;</returns>
        List<EdiFabricWebApiModelsX12Acknowledgment> AcknowledgeX12 (System.IO.Stream ediFile, string readMode = null, string accept = null, string charSet = null, bool? continueOnError = null, bool? skipTrailerValidation = null, string syntaxSet = null, bool? transactionDuplicate = null, bool? groupDuplicate = null, string technicalAck = null, bool? generateForValidTransactions = null, bool? allowPartial = null, int? transactionControlNumber = null, string ak901 = null, string ackVersion = null, bool? includeTransactions = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ediFile">EDI file to translate</param>
        /// <param name="readMode"> (optional, default to read_small)</param>
        /// <param name="accept"> (optional, default to application/json)</param>
        /// <param name="charSet"> (optional, default to utf-8)</param>
        /// <param name="continueOnError"> (optional, default to true)</param>
        /// <param name="skipTrailerValidation"> (optional, default to false)</param>
        /// <param name="syntaxSet"> (optional)</param>
        /// <param name="transactionDuplicate"> (optional, default to false)</param>
        /// <param name="groupDuplicate"> (optional, default to false)</param>
        /// <param name="technicalAck"> (optional, default to default)</param>
        /// <param name="generateForValidTransactions"> (optional, default to false)</param>
        /// <param name="allowPartial"> (optional, default to false)</param>
        /// <param name="transactionControlNumber"> (optional, default to 1)</param>
        /// <param name="ak901"> (optional, default to e)</param>
        /// <param name="ackVersion"> (optional, default to 4010_997)</param>
        /// <param name="includeTransactions"> (optional, default to false)</param>
        /// <returns>ApiResponse of List&lt;EdiFabricWebApiModelsX12Acknowledgment&gt;</returns>
        ApiResponse<List<EdiFabricWebApiModelsX12Acknowledgment>> AcknowledgeX12WithHttpInfo (System.IO.Stream ediFile, string readMode = null, string accept = null, string charSet = null, bool? continueOnError = null, bool? skipTrailerValidation = null, string syntaxSet = null, bool? transactionDuplicate = null, bool? groupDuplicate = null, string technicalAck = null, bool? generateForValidTransactions = null, bool? allowPartial = null, int? transactionControlNumber = null, string ak901 = null, string ackVersion = null, bool? includeTransactions = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ediFile">EDI file to translate</param>
        /// <param name="readMode"> (optional, default to read_small)</param>
        /// <param name="accept"> (optional, default to application/json)</param>
        /// <param name="charSet"> (optional, default to utf-8)</param>
        /// <param name="continueOnError"> (optional, default to true)</param>
        /// <param name="skipTrailerValidation"> (optional, default to false)</param>
        /// <param name="decimalPoint"> (optional, default to .)</param>
        /// <param name="syntaxSet"> (optional)</param>
        /// <param name="transactionDuplicate"> (optional, default to false)</param>
        /// <param name="groupDuplicate"> (optional, default to false)</param>
        /// <param name="technicalAck"> (optional, default to default)</param>
        /// <param name="generateForValidTransactions"> (optional, default to false)</param>
        /// <param name="allowPartial"> (optional, default to false)</param>
        /// <param name="transactionControlNumber"> (optional, default to 1)</param>
        /// <param name="eancomSyntax"> (optional)</param>
        /// <param name="includeTransactions"> (optional, default to false)</param>
        /// <returns>Task of List&lt;EdiFabricWebApiModelsEdifactAcknowledgment&gt;</returns>
        System.Threading.Tasks.Task<List<EdiFabricWebApiModelsEdifactAcknowledgment>> AcknowledgeEdifactAsync (System.IO.Stream ediFile, string readMode = null, string accept = null, string charSet = null, bool? continueOnError = null, bool? skipTrailerValidation = null, string decimalPoint = null, string syntaxSet = null, bool? transactionDuplicate = null, bool? groupDuplicate = null, string technicalAck = null, bool? generateForValidTransactions = null, bool? allowPartial = null, int? transactionControlNumber = null, string eancomSyntax = null, bool? includeTransactions = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ediFile">EDI file to translate</param>
        /// <param name="readMode"> (optional, default to read_small)</param>
        /// <param name="accept"> (optional, default to application/json)</param>
        /// <param name="charSet"> (optional, default to utf-8)</param>
        /// <param name="continueOnError"> (optional, default to true)</param>
        /// <param name="skipTrailerValidation"> (optional, default to false)</param>
        /// <param name="decimalPoint"> (optional, default to .)</param>
        /// <param name="syntaxSet"> (optional)</param>
        /// <param name="transactionDuplicate"> (optional, default to false)</param>
        /// <param name="groupDuplicate"> (optional, default to false)</param>
        /// <param name="technicalAck"> (optional, default to default)</param>
        /// <param name="generateForValidTransactions"> (optional, default to false)</param>
        /// <param name="allowPartial"> (optional, default to false)</param>
        /// <param name="transactionControlNumber"> (optional, default to 1)</param>
        /// <param name="eancomSyntax"> (optional)</param>
        /// <param name="includeTransactions"> (optional, default to false)</param>
        /// <returns>Task of ApiResponse (List&lt;EdiFabricWebApiModelsEdifactAcknowledgment&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<EdiFabricWebApiModelsEdifactAcknowledgment>>> AcknowledgeEdifactAsyncWithHttpInfo (System.IO.Stream ediFile, string readMode = null, string accept = null, string charSet = null, bool? continueOnError = null, bool? skipTrailerValidation = null, string decimalPoint = null, string syntaxSet = null, bool? transactionDuplicate = null, bool? groupDuplicate = null, string technicalAck = null, bool? generateForValidTransactions = null, bool? allowPartial = null, int? transactionControlNumber = null, string eancomSyntax = null, bool? includeTransactions = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ediFile">EDI file to translate</param>
        /// <param name="readMode"> (optional, default to read_small)</param>
        /// <param name="accept"> (optional, default to application/json)</param>
        /// <param name="charSet"> (optional, default to utf-8)</param>
        /// <param name="continueOnError"> (optional, default to true)</param>
        /// <param name="skipTrailerValidation"> (optional, default to false)</param>
        /// <param name="syntaxSet"> (optional)</param>
        /// <param name="transactionDuplicate"> (optional, default to false)</param>
        /// <param name="groupDuplicate"> (optional, default to false)</param>
        /// <param name="technicalAck"> (optional, default to default)</param>
        /// <param name="generateForValidTransactions"> (optional, default to false)</param>
        /// <param name="allowPartial"> (optional, default to false)</param>
        /// <param name="transactionControlNumber"> (optional, default to 1)</param>
        /// <param name="ak901"> (optional, default to e)</param>
        /// <param name="ackVersion"> (optional, default to 4010_997)</param>
        /// <param name="includeTransactions"> (optional, default to false)</param>
        /// <returns>Task of List&lt;EdiFabricWebApiModelsX12Acknowledgment&gt;</returns>
        System.Threading.Tasks.Task<List<EdiFabricWebApiModelsX12Acknowledgment>> AcknowledgeX12Async (System.IO.Stream ediFile, string readMode = null, string accept = null, string charSet = null, bool? continueOnError = null, bool? skipTrailerValidation = null, string syntaxSet = null, bool? transactionDuplicate = null, bool? groupDuplicate = null, string technicalAck = null, bool? generateForValidTransactions = null, bool? allowPartial = null, int? transactionControlNumber = null, string ak901 = null, string ackVersion = null, bool? includeTransactions = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ediFile">EDI file to translate</param>
        /// <param name="readMode"> (optional, default to read_small)</param>
        /// <param name="accept"> (optional, default to application/json)</param>
        /// <param name="charSet"> (optional, default to utf-8)</param>
        /// <param name="continueOnError"> (optional, default to true)</param>
        /// <param name="skipTrailerValidation"> (optional, default to false)</param>
        /// <param name="syntaxSet"> (optional)</param>
        /// <param name="transactionDuplicate"> (optional, default to false)</param>
        /// <param name="groupDuplicate"> (optional, default to false)</param>
        /// <param name="technicalAck"> (optional, default to default)</param>
        /// <param name="generateForValidTransactions"> (optional, default to false)</param>
        /// <param name="allowPartial"> (optional, default to false)</param>
        /// <param name="transactionControlNumber"> (optional, default to 1)</param>
        /// <param name="ak901"> (optional, default to e)</param>
        /// <param name="ackVersion"> (optional, default to 4010_997)</param>
        /// <param name="includeTransactions"> (optional, default to false)</param>
        /// <returns>Task of ApiResponse (List&lt;EdiFabricWebApiModelsX12Acknowledgment&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<EdiFabricWebApiModelsX12Acknowledgment>>> AcknowledgeX12AsyncWithHttpInfo (System.IO.Stream ediFile, string readMode = null, string accept = null, string charSet = null, bool? continueOnError = null, bool? skipTrailerValidation = null, string syntaxSet = null, bool? transactionDuplicate = null, bool? groupDuplicate = null, string technicalAck = null, bool? generateForValidTransactions = null, bool? allowPartial = null, int? transactionControlNumber = null, string ak901 = null, string ackVersion = null, bool? includeTransactions = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AcknowledgeApi : IAcknowledgeApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AcknowledgeApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AcknowledgeApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AcknowledgeApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AcknowledgeApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ediFile">EDI file to translate</param>
        /// <param name="readMode"> (optional, default to read_small)</param>
        /// <param name="accept"> (optional, default to application/json)</param>
        /// <param name="charSet"> (optional, default to utf-8)</param>
        /// <param name="continueOnError"> (optional, default to true)</param>
        /// <param name="skipTrailerValidation"> (optional, default to false)</param>
        /// <param name="decimalPoint"> (optional, default to .)</param>
        /// <param name="syntaxSet"> (optional)</param>
        /// <param name="transactionDuplicate"> (optional, default to false)</param>
        /// <param name="groupDuplicate"> (optional, default to false)</param>
        /// <param name="technicalAck"> (optional, default to default)</param>
        /// <param name="generateForValidTransactions"> (optional, default to false)</param>
        /// <param name="allowPartial"> (optional, default to false)</param>
        /// <param name="transactionControlNumber"> (optional, default to 1)</param>
        /// <param name="eancomSyntax"> (optional)</param>
        /// <param name="includeTransactions"> (optional, default to false)</param>
        /// <returns>List&lt;EdiFabricWebApiModelsEdifactAcknowledgment&gt;</returns>
        public List<EdiFabricWebApiModelsEdifactAcknowledgment> AcknowledgeEdifact (System.IO.Stream ediFile, string readMode = null, string accept = null, string charSet = null, bool? continueOnError = null, bool? skipTrailerValidation = null, string decimalPoint = null, string syntaxSet = null, bool? transactionDuplicate = null, bool? groupDuplicate = null, string technicalAck = null, bool? generateForValidTransactions = null, bool? allowPartial = null, int? transactionControlNumber = null, string eancomSyntax = null, bool? includeTransactions = null)
        {
             ApiResponse<List<EdiFabricWebApiModelsEdifactAcknowledgment>> localVarResponse = AcknowledgeEdifactWithHttpInfo(ediFile, readMode, accept, charSet, continueOnError, skipTrailerValidation, decimalPoint, syntaxSet, transactionDuplicate, groupDuplicate, technicalAck, generateForValidTransactions, allowPartial, transactionControlNumber, eancomSyntax, includeTransactions);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ediFile">EDI file to translate</param>
        /// <param name="readMode"> (optional, default to read_small)</param>
        /// <param name="accept"> (optional, default to application/json)</param>
        /// <param name="charSet"> (optional, default to utf-8)</param>
        /// <param name="continueOnError"> (optional, default to true)</param>
        /// <param name="skipTrailerValidation"> (optional, default to false)</param>
        /// <param name="decimalPoint"> (optional, default to .)</param>
        /// <param name="syntaxSet"> (optional)</param>
        /// <param name="transactionDuplicate"> (optional, default to false)</param>
        /// <param name="groupDuplicate"> (optional, default to false)</param>
        /// <param name="technicalAck"> (optional, default to default)</param>
        /// <param name="generateForValidTransactions"> (optional, default to false)</param>
        /// <param name="allowPartial"> (optional, default to false)</param>
        /// <param name="transactionControlNumber"> (optional, default to 1)</param>
        /// <param name="eancomSyntax"> (optional)</param>
        /// <param name="includeTransactions"> (optional, default to false)</param>
        /// <returns>ApiResponse of List&lt;EdiFabricWebApiModelsEdifactAcknowledgment&gt;</returns>
        public ApiResponse< List<EdiFabricWebApiModelsEdifactAcknowledgment> > AcknowledgeEdifactWithHttpInfo (System.IO.Stream ediFile, string readMode = null, string accept = null, string charSet = null, bool? continueOnError = null, bool? skipTrailerValidation = null, string decimalPoint = null, string syntaxSet = null, bool? transactionDuplicate = null, bool? groupDuplicate = null, string technicalAck = null, bool? generateForValidTransactions = null, bool? allowPartial = null, int? transactionControlNumber = null, string eancomSyntax = null, bool? includeTransactions = null)
        {
            // verify the required parameter 'ediFile' is set
            if (ediFile == null)
                throw new ApiException(400, "Missing required parameter 'ediFile' when calling AcknowledgeApi->AcknowledgeEdifact");

            var localVarPath = "/acknowledge/edifact";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (readMode != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "read_mode", readMode)); // query parameter
            if (accept != null) localVarHeaderParams.Add("Accept", this.Configuration.ApiClient.ParameterToString(accept)); // header parameter
            if (charSet != null) localVarFormParams.Add("char_set", this.Configuration.ApiClient.ParameterToString(charSet)); // form parameter
            if (continueOnError != null) localVarFormParams.Add("continue_on_error", this.Configuration.ApiClient.ParameterToString(continueOnError)); // form parameter
            if (skipTrailerValidation != null) localVarFormParams.Add("skip_trailer_validation", this.Configuration.ApiClient.ParameterToString(skipTrailerValidation)); // form parameter
            if (decimalPoint != null) localVarFormParams.Add("decimal_point", this.Configuration.ApiClient.ParameterToString(decimalPoint)); // form parameter
            if (syntaxSet != null) localVarFormParams.Add("syntax_set", this.Configuration.ApiClient.ParameterToString(syntaxSet)); // form parameter
            if (transactionDuplicate != null) localVarFormParams.Add("transaction_duplicate", this.Configuration.ApiClient.ParameterToString(transactionDuplicate)); // form parameter
            if (groupDuplicate != null) localVarFormParams.Add("group_duplicate", this.Configuration.ApiClient.ParameterToString(groupDuplicate)); // form parameter
            if (technicalAck != null) localVarFormParams.Add("technical_ack", this.Configuration.ApiClient.ParameterToString(technicalAck)); // form parameter
            if (generateForValidTransactions != null) localVarFormParams.Add("generate_for_valid_transactions", this.Configuration.ApiClient.ParameterToString(generateForValidTransactions)); // form parameter
            if (allowPartial != null) localVarFormParams.Add("allow_partial", this.Configuration.ApiClient.ParameterToString(allowPartial)); // form parameter
            if (transactionControlNumber != null) localVarFormParams.Add("transaction_control_number", this.Configuration.ApiClient.ParameterToString(transactionControlNumber)); // form parameter
            if (eancomSyntax != null) localVarFormParams.Add("eancom_syntax", this.Configuration.ApiClient.ParameterToString(eancomSyntax)); // form parameter
            if (includeTransactions != null) localVarFormParams.Add("include_transactions", this.Configuration.ApiClient.ParameterToString(includeTransactions)); // form parameter
            if (ediFile != null) localVarFileParams.Add("edi_file", this.Configuration.ApiClient.ParameterToFile("edi_file", ediFile));


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AcknowledgeEdifact", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<EdiFabricWebApiModelsEdifactAcknowledgment>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<EdiFabricWebApiModelsEdifactAcknowledgment>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<EdiFabricWebApiModelsEdifactAcknowledgment>)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ediFile">EDI file to translate</param>
        /// <param name="readMode"> (optional, default to read_small)</param>
        /// <param name="accept"> (optional, default to application/json)</param>
        /// <param name="charSet"> (optional, default to utf-8)</param>
        /// <param name="continueOnError"> (optional, default to true)</param>
        /// <param name="skipTrailerValidation"> (optional, default to false)</param>
        /// <param name="decimalPoint"> (optional, default to .)</param>
        /// <param name="syntaxSet"> (optional)</param>
        /// <param name="transactionDuplicate"> (optional, default to false)</param>
        /// <param name="groupDuplicate"> (optional, default to false)</param>
        /// <param name="technicalAck"> (optional, default to default)</param>
        /// <param name="generateForValidTransactions"> (optional, default to false)</param>
        /// <param name="allowPartial"> (optional, default to false)</param>
        /// <param name="transactionControlNumber"> (optional, default to 1)</param>
        /// <param name="eancomSyntax"> (optional)</param>
        /// <param name="includeTransactions"> (optional, default to false)</param>
        /// <returns>Task of List&lt;EdiFabricWebApiModelsEdifactAcknowledgment&gt;</returns>
        public async System.Threading.Tasks.Task<List<EdiFabricWebApiModelsEdifactAcknowledgment>> AcknowledgeEdifactAsync (System.IO.Stream ediFile, string readMode = null, string accept = null, string charSet = null, bool? continueOnError = null, bool? skipTrailerValidation = null, string decimalPoint = null, string syntaxSet = null, bool? transactionDuplicate = null, bool? groupDuplicate = null, string technicalAck = null, bool? generateForValidTransactions = null, bool? allowPartial = null, int? transactionControlNumber = null, string eancomSyntax = null, bool? includeTransactions = null)
        {
             ApiResponse<List<EdiFabricWebApiModelsEdifactAcknowledgment>> localVarResponse = await AcknowledgeEdifactAsyncWithHttpInfo(ediFile, readMode, accept, charSet, continueOnError, skipTrailerValidation, decimalPoint, syntaxSet, transactionDuplicate, groupDuplicate, technicalAck, generateForValidTransactions, allowPartial, transactionControlNumber, eancomSyntax, includeTransactions);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ediFile">EDI file to translate</param>
        /// <param name="readMode"> (optional, default to read_small)</param>
        /// <param name="accept"> (optional, default to application/json)</param>
        /// <param name="charSet"> (optional, default to utf-8)</param>
        /// <param name="continueOnError"> (optional, default to true)</param>
        /// <param name="skipTrailerValidation"> (optional, default to false)</param>
        /// <param name="decimalPoint"> (optional, default to .)</param>
        /// <param name="syntaxSet"> (optional)</param>
        /// <param name="transactionDuplicate"> (optional, default to false)</param>
        /// <param name="groupDuplicate"> (optional, default to false)</param>
        /// <param name="technicalAck"> (optional, default to default)</param>
        /// <param name="generateForValidTransactions"> (optional, default to false)</param>
        /// <param name="allowPartial"> (optional, default to false)</param>
        /// <param name="transactionControlNumber"> (optional, default to 1)</param>
        /// <param name="eancomSyntax"> (optional)</param>
        /// <param name="includeTransactions"> (optional, default to false)</param>
        /// <returns>Task of ApiResponse (List&lt;EdiFabricWebApiModelsEdifactAcknowledgment&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<EdiFabricWebApiModelsEdifactAcknowledgment>>> AcknowledgeEdifactAsyncWithHttpInfo (System.IO.Stream ediFile, string readMode = null, string accept = null, string charSet = null, bool? continueOnError = null, bool? skipTrailerValidation = null, string decimalPoint = null, string syntaxSet = null, bool? transactionDuplicate = null, bool? groupDuplicate = null, string technicalAck = null, bool? generateForValidTransactions = null, bool? allowPartial = null, int? transactionControlNumber = null, string eancomSyntax = null, bool? includeTransactions = null)
        {
            // verify the required parameter 'ediFile' is set
            if (ediFile == null)
                throw new ApiException(400, "Missing required parameter 'ediFile' when calling AcknowledgeApi->AcknowledgeEdifact");

            var localVarPath = "/acknowledge/edifact";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (readMode != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "read_mode", readMode)); // query parameter
            if (accept != null) localVarHeaderParams.Add("Accept", this.Configuration.ApiClient.ParameterToString(accept)); // header parameter
            if (charSet != null) localVarFormParams.Add("char_set", this.Configuration.ApiClient.ParameterToString(charSet)); // form parameter
            if (continueOnError != null) localVarFormParams.Add("continue_on_error", this.Configuration.ApiClient.ParameterToString(continueOnError)); // form parameter
            if (skipTrailerValidation != null) localVarFormParams.Add("skip_trailer_validation", this.Configuration.ApiClient.ParameterToString(skipTrailerValidation)); // form parameter
            if (decimalPoint != null) localVarFormParams.Add("decimal_point", this.Configuration.ApiClient.ParameterToString(decimalPoint)); // form parameter
            if (syntaxSet != null) localVarFormParams.Add("syntax_set", this.Configuration.ApiClient.ParameterToString(syntaxSet)); // form parameter
            if (transactionDuplicate != null) localVarFormParams.Add("transaction_duplicate", this.Configuration.ApiClient.ParameterToString(transactionDuplicate)); // form parameter
            if (groupDuplicate != null) localVarFormParams.Add("group_duplicate", this.Configuration.ApiClient.ParameterToString(groupDuplicate)); // form parameter
            if (technicalAck != null) localVarFormParams.Add("technical_ack", this.Configuration.ApiClient.ParameterToString(technicalAck)); // form parameter
            if (generateForValidTransactions != null) localVarFormParams.Add("generate_for_valid_transactions", this.Configuration.ApiClient.ParameterToString(generateForValidTransactions)); // form parameter
            if (allowPartial != null) localVarFormParams.Add("allow_partial", this.Configuration.ApiClient.ParameterToString(allowPartial)); // form parameter
            if (transactionControlNumber != null) localVarFormParams.Add("transaction_control_number", this.Configuration.ApiClient.ParameterToString(transactionControlNumber)); // form parameter
            if (eancomSyntax != null) localVarFormParams.Add("eancom_syntax", this.Configuration.ApiClient.ParameterToString(eancomSyntax)); // form parameter
            if (includeTransactions != null) localVarFormParams.Add("include_transactions", this.Configuration.ApiClient.ParameterToString(includeTransactions)); // form parameter
            if (ediFile != null) localVarFileParams.Add("edi_file", this.Configuration.ApiClient.ParameterToFile("edi_file", ediFile));


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AcknowledgeEdifact", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<EdiFabricWebApiModelsEdifactAcknowledgment>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<EdiFabricWebApiModelsEdifactAcknowledgment>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<EdiFabricWebApiModelsEdifactAcknowledgment>)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ediFile">EDI file to translate</param>
        /// <param name="readMode"> (optional, default to read_small)</param>
        /// <param name="accept"> (optional, default to application/json)</param>
        /// <param name="charSet"> (optional, default to utf-8)</param>
        /// <param name="continueOnError"> (optional, default to true)</param>
        /// <param name="skipTrailerValidation"> (optional, default to false)</param>
        /// <param name="syntaxSet"> (optional)</param>
        /// <param name="transactionDuplicate"> (optional, default to false)</param>
        /// <param name="groupDuplicate"> (optional, default to false)</param>
        /// <param name="technicalAck"> (optional, default to default)</param>
        /// <param name="generateForValidTransactions"> (optional, default to false)</param>
        /// <param name="allowPartial"> (optional, default to false)</param>
        /// <param name="transactionControlNumber"> (optional, default to 1)</param>
        /// <param name="ak901"> (optional, default to e)</param>
        /// <param name="ackVersion"> (optional, default to 4010_997)</param>
        /// <param name="includeTransactions"> (optional, default to false)</param>
        /// <returns>List&lt;EdiFabricWebApiModelsX12Acknowledgment&gt;</returns>
        public List<EdiFabricWebApiModelsX12Acknowledgment> AcknowledgeX12 (System.IO.Stream ediFile, string readMode = null, string accept = null, string charSet = null, bool? continueOnError = null, bool? skipTrailerValidation = null, string syntaxSet = null, bool? transactionDuplicate = null, bool? groupDuplicate = null, string technicalAck = null, bool? generateForValidTransactions = null, bool? allowPartial = null, int? transactionControlNumber = null, string ak901 = null, string ackVersion = null, bool? includeTransactions = null)
        {
             ApiResponse<List<EdiFabricWebApiModelsX12Acknowledgment>> localVarResponse = AcknowledgeX12WithHttpInfo(ediFile, readMode, accept, charSet, continueOnError, skipTrailerValidation, syntaxSet, transactionDuplicate, groupDuplicate, technicalAck, generateForValidTransactions, allowPartial, transactionControlNumber, ak901, ackVersion, includeTransactions);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ediFile">EDI file to translate</param>
        /// <param name="readMode"> (optional, default to read_small)</param>
        /// <param name="accept"> (optional, default to application/json)</param>
        /// <param name="charSet"> (optional, default to utf-8)</param>
        /// <param name="continueOnError"> (optional, default to true)</param>
        /// <param name="skipTrailerValidation"> (optional, default to false)</param>
        /// <param name="syntaxSet"> (optional)</param>
        /// <param name="transactionDuplicate"> (optional, default to false)</param>
        /// <param name="groupDuplicate"> (optional, default to false)</param>
        /// <param name="technicalAck"> (optional, default to default)</param>
        /// <param name="generateForValidTransactions"> (optional, default to false)</param>
        /// <param name="allowPartial"> (optional, default to false)</param>
        /// <param name="transactionControlNumber"> (optional, default to 1)</param>
        /// <param name="ak901"> (optional, default to e)</param>
        /// <param name="ackVersion"> (optional, default to 4010_997)</param>
        /// <param name="includeTransactions"> (optional, default to false)</param>
        /// <returns>ApiResponse of List&lt;EdiFabricWebApiModelsX12Acknowledgment&gt;</returns>
        public ApiResponse< List<EdiFabricWebApiModelsX12Acknowledgment> > AcknowledgeX12WithHttpInfo (System.IO.Stream ediFile, string readMode = null, string accept = null, string charSet = null, bool? continueOnError = null, bool? skipTrailerValidation = null, string syntaxSet = null, bool? transactionDuplicate = null, bool? groupDuplicate = null, string technicalAck = null, bool? generateForValidTransactions = null, bool? allowPartial = null, int? transactionControlNumber = null, string ak901 = null, string ackVersion = null, bool? includeTransactions = null)
        {
            // verify the required parameter 'ediFile' is set
            if (ediFile == null)
                throw new ApiException(400, "Missing required parameter 'ediFile' when calling AcknowledgeApi->AcknowledgeX12");

            var localVarPath = "/acknowledge/x12";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (readMode != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "read_mode", readMode)); // query parameter
            if (accept != null) localVarHeaderParams.Add("Accept", this.Configuration.ApiClient.ParameterToString(accept)); // header parameter
            if (charSet != null) localVarFormParams.Add("char_set", this.Configuration.ApiClient.ParameterToString(charSet)); // form parameter
            if (continueOnError != null) localVarFormParams.Add("continue_on_error", this.Configuration.ApiClient.ParameterToString(continueOnError)); // form parameter
            if (skipTrailerValidation != null) localVarFormParams.Add("skip_trailer_validation", this.Configuration.ApiClient.ParameterToString(skipTrailerValidation)); // form parameter
            if (syntaxSet != null) localVarFormParams.Add("syntax_set", this.Configuration.ApiClient.ParameterToString(syntaxSet)); // form parameter
            if (transactionDuplicate != null) localVarFormParams.Add("transaction_duplicate", this.Configuration.ApiClient.ParameterToString(transactionDuplicate)); // form parameter
            if (groupDuplicate != null) localVarFormParams.Add("group_duplicate", this.Configuration.ApiClient.ParameterToString(groupDuplicate)); // form parameter
            if (technicalAck != null) localVarFormParams.Add("technical_ack", this.Configuration.ApiClient.ParameterToString(technicalAck)); // form parameter
            if (generateForValidTransactions != null) localVarFormParams.Add("generate_for_valid_transactions", this.Configuration.ApiClient.ParameterToString(generateForValidTransactions)); // form parameter
            if (allowPartial != null) localVarFormParams.Add("allow_partial", this.Configuration.ApiClient.ParameterToString(allowPartial)); // form parameter
            if (transactionControlNumber != null) localVarFormParams.Add("transaction_control_number", this.Configuration.ApiClient.ParameterToString(transactionControlNumber)); // form parameter
            if (ak901 != null) localVarFormParams.Add("ak901", this.Configuration.ApiClient.ParameterToString(ak901)); // form parameter
            if (ackVersion != null) localVarFormParams.Add("ack_version", this.Configuration.ApiClient.ParameterToString(ackVersion)); // form parameter
            if (includeTransactions != null) localVarFormParams.Add("include_transactions", this.Configuration.ApiClient.ParameterToString(includeTransactions)); // form parameter
            if (ediFile != null) localVarFileParams.Add("edi_file", this.Configuration.ApiClient.ParameterToFile("edi_file", ediFile));


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AcknowledgeX12", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<EdiFabricWebApiModelsX12Acknowledgment>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<EdiFabricWebApiModelsX12Acknowledgment>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<EdiFabricWebApiModelsX12Acknowledgment>)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ediFile">EDI file to translate</param>
        /// <param name="readMode"> (optional, default to read_small)</param>
        /// <param name="accept"> (optional, default to application/json)</param>
        /// <param name="charSet"> (optional, default to utf-8)</param>
        /// <param name="continueOnError"> (optional, default to true)</param>
        /// <param name="skipTrailerValidation"> (optional, default to false)</param>
        /// <param name="syntaxSet"> (optional)</param>
        /// <param name="transactionDuplicate"> (optional, default to false)</param>
        /// <param name="groupDuplicate"> (optional, default to false)</param>
        /// <param name="technicalAck"> (optional, default to default)</param>
        /// <param name="generateForValidTransactions"> (optional, default to false)</param>
        /// <param name="allowPartial"> (optional, default to false)</param>
        /// <param name="transactionControlNumber"> (optional, default to 1)</param>
        /// <param name="ak901"> (optional, default to e)</param>
        /// <param name="ackVersion"> (optional, default to 4010_997)</param>
        /// <param name="includeTransactions"> (optional, default to false)</param>
        /// <returns>Task of List&lt;EdiFabricWebApiModelsX12Acknowledgment&gt;</returns>
        public async System.Threading.Tasks.Task<List<EdiFabricWebApiModelsX12Acknowledgment>> AcknowledgeX12Async (System.IO.Stream ediFile, string readMode = null, string accept = null, string charSet = null, bool? continueOnError = null, bool? skipTrailerValidation = null, string syntaxSet = null, bool? transactionDuplicate = null, bool? groupDuplicate = null, string technicalAck = null, bool? generateForValidTransactions = null, bool? allowPartial = null, int? transactionControlNumber = null, string ak901 = null, string ackVersion = null, bool? includeTransactions = null)
        {
             ApiResponse<List<EdiFabricWebApiModelsX12Acknowledgment>> localVarResponse = await AcknowledgeX12AsyncWithHttpInfo(ediFile, readMode, accept, charSet, continueOnError, skipTrailerValidation, syntaxSet, transactionDuplicate, groupDuplicate, technicalAck, generateForValidTransactions, allowPartial, transactionControlNumber, ak901, ackVersion, includeTransactions);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ediFile">EDI file to translate</param>
        /// <param name="readMode"> (optional, default to read_small)</param>
        /// <param name="accept"> (optional, default to application/json)</param>
        /// <param name="charSet"> (optional, default to utf-8)</param>
        /// <param name="continueOnError"> (optional, default to true)</param>
        /// <param name="skipTrailerValidation"> (optional, default to false)</param>
        /// <param name="syntaxSet"> (optional)</param>
        /// <param name="transactionDuplicate"> (optional, default to false)</param>
        /// <param name="groupDuplicate"> (optional, default to false)</param>
        /// <param name="technicalAck"> (optional, default to default)</param>
        /// <param name="generateForValidTransactions"> (optional, default to false)</param>
        /// <param name="allowPartial"> (optional, default to false)</param>
        /// <param name="transactionControlNumber"> (optional, default to 1)</param>
        /// <param name="ak901"> (optional, default to e)</param>
        /// <param name="ackVersion"> (optional, default to 4010_997)</param>
        /// <param name="includeTransactions"> (optional, default to false)</param>
        /// <returns>Task of ApiResponse (List&lt;EdiFabricWebApiModelsX12Acknowledgment&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<EdiFabricWebApiModelsX12Acknowledgment>>> AcknowledgeX12AsyncWithHttpInfo (System.IO.Stream ediFile, string readMode = null, string accept = null, string charSet = null, bool? continueOnError = null, bool? skipTrailerValidation = null, string syntaxSet = null, bool? transactionDuplicate = null, bool? groupDuplicate = null, string technicalAck = null, bool? generateForValidTransactions = null, bool? allowPartial = null, int? transactionControlNumber = null, string ak901 = null, string ackVersion = null, bool? includeTransactions = null)
        {
            // verify the required parameter 'ediFile' is set
            if (ediFile == null)
                throw new ApiException(400, "Missing required parameter 'ediFile' when calling AcknowledgeApi->AcknowledgeX12");

            var localVarPath = "/acknowledge/x12";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (readMode != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "read_mode", readMode)); // query parameter
            if (accept != null) localVarHeaderParams.Add("Accept", this.Configuration.ApiClient.ParameterToString(accept)); // header parameter
            if (charSet != null) localVarFormParams.Add("char_set", this.Configuration.ApiClient.ParameterToString(charSet)); // form parameter
            if (continueOnError != null) localVarFormParams.Add("continue_on_error", this.Configuration.ApiClient.ParameterToString(continueOnError)); // form parameter
            if (skipTrailerValidation != null) localVarFormParams.Add("skip_trailer_validation", this.Configuration.ApiClient.ParameterToString(skipTrailerValidation)); // form parameter
            if (syntaxSet != null) localVarFormParams.Add("syntax_set", this.Configuration.ApiClient.ParameterToString(syntaxSet)); // form parameter
            if (transactionDuplicate != null) localVarFormParams.Add("transaction_duplicate", this.Configuration.ApiClient.ParameterToString(transactionDuplicate)); // form parameter
            if (groupDuplicate != null) localVarFormParams.Add("group_duplicate", this.Configuration.ApiClient.ParameterToString(groupDuplicate)); // form parameter
            if (technicalAck != null) localVarFormParams.Add("technical_ack", this.Configuration.ApiClient.ParameterToString(technicalAck)); // form parameter
            if (generateForValidTransactions != null) localVarFormParams.Add("generate_for_valid_transactions", this.Configuration.ApiClient.ParameterToString(generateForValidTransactions)); // form parameter
            if (allowPartial != null) localVarFormParams.Add("allow_partial", this.Configuration.ApiClient.ParameterToString(allowPartial)); // form parameter
            if (transactionControlNumber != null) localVarFormParams.Add("transaction_control_number", this.Configuration.ApiClient.ParameterToString(transactionControlNumber)); // form parameter
            if (ak901 != null) localVarFormParams.Add("ak901", this.Configuration.ApiClient.ParameterToString(ak901)); // form parameter
            if (ackVersion != null) localVarFormParams.Add("ack_version", this.Configuration.ApiClient.ParameterToString(ackVersion)); // form parameter
            if (includeTransactions != null) localVarFormParams.Add("include_transactions", this.Configuration.ApiClient.ParameterToString(includeTransactions)); // form parameter
            if (ediFile != null) localVarFileParams.Add("edi_file", this.Configuration.ApiClient.ParameterToFile("edi_file", ediFile));


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AcknowledgeX12", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<EdiFabricWebApiModelsX12Acknowledgment>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<EdiFabricWebApiModelsX12Acknowledgment>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<EdiFabricWebApiModelsX12Acknowledgment>)));
        }

    }
}
