<?php
/**
 * EdiFabricWebApiModelsX12AcknowledgmentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EdiFabric API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.4
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EdiFabricWebApiModelsX12AcknowledgmentTest Class Doc Comment
 *
 * @category    Class
 * @description EdiFabricWebApiModelsX12Acknowledgment
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EdiFabricWebApiModelsX12AcknowledgmentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EdiFabricWebApiModelsX12Acknowledgment"
     */
    public function testEdiFabricWebApiModelsX12Acknowledgment()
    {
    }

    /**
     * Test attribute "original_isa"
     */
    public function testPropertyOriginalIsa()
    {
    }

    /**
     * Test attribute "original_gs"
     */
    public function testPropertyOriginalGs()
    {
    }

    /**
     * Test attribute "ack_type"
     */
    public function testPropertyAckType()
    {
    }

    /**
     * Test attribute "ack"
     */
    public function testPropertyAck()
    {
    }

    /**
     * Test attribute "original_transactions"
     */
    public function testPropertyOriginalTransactions()
    {
    }
}
