<?php
/**
 * EdiFabricCoreModelEdiEdifactUNBTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EdiFabric API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.4
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EdiFabricCoreModelEdiEdifactUNBTest Class Doc Comment
 *
 * @category    Class
 * @description EdiFabricCoreModelEdiEdifactUNB
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EdiFabricCoreModelEdiEdifactUNBTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EdiFabricCoreModelEdiEdifactUNB"
     */
    public function testEdiFabricCoreModelEdiEdifactUNB()
    {
    }

    /**
     * Test attribute "syntaxidentifie_r_1"
     */
    public function testPropertySyntaxidentifieR1()
    {
    }

    /**
     * Test attribute "interchangesende_r_2"
     */
    public function testPropertyInterchangesendeR2()
    {
    }

    /**
     * Test attribute "interchangerecipien_t_3"
     */
    public function testPropertyInterchangerecipienT3()
    {
    }

    /**
     * Test attribute "dateandtimeofpreparatio_n_4"
     */
    public function testPropertyDateandtimeofpreparatioN4()
    {
    }

    /**
     * Test attribute "interchange_control_reference_5"
     */
    public function testPropertyInterchangeControlReference5()
    {
    }

    /**
     * Test attribute "recipientsreferencepassworddetail_s_6"
     */
    public function testPropertyRecipientsreferencepassworddetailS6()
    {
    }

    /**
     * Test attribute "application_reference_7"
     */
    public function testPropertyApplicationReference7()
    {
    }

    /**
     * Test attribute "processing_priority_code_8"
     */
    public function testPropertyProcessingPriorityCode8()
    {
    }

    /**
     * Test attribute "acknowledgement_request_9"
     */
    public function testPropertyAcknowledgementRequest9()
    {
    }

    /**
     * Test attribute "interchange_agreement_identifier_10"
     */
    public function testPropertyInterchangeAgreementIdentifier10()
    {
    }

    /**
     * Test attribute "test_indicator_11"
     */
    public function testPropertyTestIndicator11()
    {
    }
}
