<?php
/**
 * EdiFabricCoreModelEdiEdifactS004Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EdiFabric API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.4
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EdiFabricCoreModelEdiEdifactS004Test Class Doc Comment
 *
 * @category    Class
 * @description EdiFabricCoreModelEdiEdifactS004
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EdiFabricCoreModelEdiEdifactS004Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EdiFabricCoreModelEdiEdifactS004"
     */
    public function testEdiFabricCoreModelEdiEdifactS004()
    {
    }

    /**
     * Test attribute "date_1"
     */
    public function testPropertyDate1()
    {
    }

    /**
     * Test attribute "time_2"
     */
    public function testPropertyTime2()
    {
    }
}
