/**
 * EdiFabric API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EdiFabricApi) {
      root.EdiFabricApi = {};
    }
    root.EdiFabricApi.EdiFabricCoreModelEdiEdifactS004 = factory(root.EdiFabricApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The EdiFabricCoreModelEdiEdifactS004 model module.
   * @module model/EdiFabricCoreModelEdiEdifactS004
   * @version v1
   */

  /**
   * Constructs a new <code>EdiFabricCoreModelEdiEdifactS004</code>.
   * @alias module:model/EdiFabricCoreModelEdiEdifactS004
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>EdiFabricCoreModelEdiEdifactS004</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EdiFabricCoreModelEdiEdifactS004} obj Optional instance to populate.
   * @return {module:model/EdiFabricCoreModelEdiEdifactS004} The populated <code>EdiFabricCoreModelEdiEdifactS004</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('date_1')) {
        obj['date_1'] = ApiClient.convertToType(data['date_1'], 'String');
      }
      if (data.hasOwnProperty('time_2')) {
        obj['time_2'] = ApiClient.convertToType(data['time_2'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} date_1
   */
  exports.prototype['date_1'] = undefined;
  /**
   * @member {String} time_2
   */
  exports.prototype['time_2'] = undefined;



  return exports;
}));


