/**
 * EdiFabric API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EdiFabricApi) {
      root.EdiFabricApi = {};
    }
    root.EdiFabricApi.EdiFabricCoreModelEdiX12ISA = factory(root.EdiFabricApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The EdiFabricCoreModelEdiX12ISA model module.
   * @module model/EdiFabricCoreModelEdiX12ISA
   * @version v1
   */

  /**
   * Constructs a new <code>EdiFabricCoreModelEdiX12ISA</code>.
   * @alias module:model/EdiFabricCoreModelEdiX12ISA
   * @class
   */
  var exports = function() {
    var _this = this;

















  };

  /**
   * Constructs a <code>EdiFabricCoreModelEdiX12ISA</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EdiFabricCoreModelEdiX12ISA} obj Optional instance to populate.
   * @return {module:model/EdiFabricCoreModelEdiX12ISA} The populated <code>EdiFabricCoreModelEdiX12ISA</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('authorizationInformationQualifier_1')) {
        obj['authorizationInformationQualifier_1'] = ApiClient.convertToType(data['authorizationInformationQualifier_1'], 'String');
      }
      if (data.hasOwnProperty('authorizationInformation_2')) {
        obj['authorizationInformation_2'] = ApiClient.convertToType(data['authorizationInformation_2'], 'String');
      }
      if (data.hasOwnProperty('securityInformationQualifier_3')) {
        obj['securityInformationQualifier_3'] = ApiClient.convertToType(data['securityInformationQualifier_3'], 'String');
      }
      if (data.hasOwnProperty('securityInformation_4')) {
        obj['securityInformation_4'] = ApiClient.convertToType(data['securityInformation_4'], 'String');
      }
      if (data.hasOwnProperty('senderIDQualifier_5')) {
        obj['senderIDQualifier_5'] = ApiClient.convertToType(data['senderIDQualifier_5'], 'String');
      }
      if (data.hasOwnProperty('interchangeSenderID_6')) {
        obj['interchangeSenderID_6'] = ApiClient.convertToType(data['interchangeSenderID_6'], 'String');
      }
      if (data.hasOwnProperty('receiverIDQualifier_7')) {
        obj['receiverIDQualifier_7'] = ApiClient.convertToType(data['receiverIDQualifier_7'], 'String');
      }
      if (data.hasOwnProperty('interchangeReceiverID_8')) {
        obj['interchangeReceiverID_8'] = ApiClient.convertToType(data['interchangeReceiverID_8'], 'String');
      }
      if (data.hasOwnProperty('interchangeDate_9')) {
        obj['interchangeDate_9'] = ApiClient.convertToType(data['interchangeDate_9'], 'String');
      }
      if (data.hasOwnProperty('interchangeTime_10')) {
        obj['interchangeTime_10'] = ApiClient.convertToType(data['interchangeTime_10'], 'String');
      }
      if (data.hasOwnProperty('interchangeControlStandardsIdentifier_11')) {
        obj['interchangeControlStandardsIdentifier_11'] = ApiClient.convertToType(data['interchangeControlStandardsIdentifier_11'], 'String');
      }
      if (data.hasOwnProperty('interchangeControlVersionNumber_12')) {
        obj['interchangeControlVersionNumber_12'] = ApiClient.convertToType(data['interchangeControlVersionNumber_12'], 'String');
      }
      if (data.hasOwnProperty('interchangeControlNumber_13')) {
        obj['interchangeControlNumber_13'] = ApiClient.convertToType(data['interchangeControlNumber_13'], 'String');
      }
      if (data.hasOwnProperty('acknowledgementRequested_14')) {
        obj['acknowledgementRequested_14'] = ApiClient.convertToType(data['acknowledgementRequested_14'], 'String');
      }
      if (data.hasOwnProperty('usageIndicator_15')) {
        obj['usageIndicator_15'] = ApiClient.convertToType(data['usageIndicator_15'], 'String');
      }
      if (data.hasOwnProperty('componentElementSeparator_16')) {
        obj['componentElementSeparator_16'] = ApiClient.convertToType(data['componentElementSeparator_16'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} authorizationInformationQualifier_1
   */
  exports.prototype['authorizationInformationQualifier_1'] = undefined;
  /**
   * @member {String} authorizationInformation_2
   */
  exports.prototype['authorizationInformation_2'] = undefined;
  /**
   * @member {String} securityInformationQualifier_3
   */
  exports.prototype['securityInformationQualifier_3'] = undefined;
  /**
   * @member {String} securityInformation_4
   */
  exports.prototype['securityInformation_4'] = undefined;
  /**
   * @member {String} senderIDQualifier_5
   */
  exports.prototype['senderIDQualifier_5'] = undefined;
  /**
   * @member {String} interchangeSenderID_6
   */
  exports.prototype['interchangeSenderID_6'] = undefined;
  /**
   * @member {String} receiverIDQualifier_7
   */
  exports.prototype['receiverIDQualifier_7'] = undefined;
  /**
   * @member {String} interchangeReceiverID_8
   */
  exports.prototype['interchangeReceiverID_8'] = undefined;
  /**
   * @member {String} interchangeDate_9
   */
  exports.prototype['interchangeDate_9'] = undefined;
  /**
   * @member {String} interchangeTime_10
   */
  exports.prototype['interchangeTime_10'] = undefined;
  /**
   * @member {String} interchangeControlStandardsIdentifier_11
   */
  exports.prototype['interchangeControlStandardsIdentifier_11'] = undefined;
  /**
   * @member {String} interchangeControlVersionNumber_12
   */
  exports.prototype['interchangeControlVersionNumber_12'] = undefined;
  /**
   * @member {String} interchangeControlNumber_13
   */
  exports.prototype['interchangeControlNumber_13'] = undefined;
  /**
   * @member {String} acknowledgementRequested_14
   */
  exports.prototype['acknowledgementRequested_14'] = undefined;
  /**
   * @member {String} usageIndicator_15
   */
  exports.prototype['usageIndicator_15'] = undefined;
  /**
   * @member {String} componentElementSeparator_16
   */
  exports.prototype['componentElementSeparator_16'] = undefined;



  return exports;
}));


