/* 
 * EdiFabric API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// EdiFabricWebApiModelsX12Group
    /// </summary>
    [DataContract]
    public partial class EdiFabricWebApiModelsX12Group :  IEquatable<EdiFabricWebApiModelsX12Group>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdiFabricWebApiModelsX12Group" /> class.
        /// </summary>
        /// <param name="gs">gs.</param>
        /// <param name="geTrailers">geTrailers.</param>
        /// <param name="transactions">transactions.</param>
        public EdiFabricWebApiModelsX12Group(EdiFabricCoreModelEdiX12GS gs = default(EdiFabricCoreModelEdiX12GS), List<EdiFabricCoreModelEdiX12GE> geTrailers = default(List<EdiFabricCoreModelEdiX12GE>), List<EdiFabricCoreModelEdiEdiMessage> transactions = default(List<EdiFabricCoreModelEdiEdiMessage>))
        {
            this.Gs = gs;
            this.GeTrailers = geTrailers;
            this.Transactions = transactions;
        }
        
        /// <summary>
        /// Gets or Sets Gs
        /// </summary>
        [DataMember(Name="gs", EmitDefaultValue=false)]
        public EdiFabricCoreModelEdiX12GS Gs { get; set; }

        /// <summary>
        /// Gets or Sets GeTrailers
        /// </summary>
        [DataMember(Name="geTrailers", EmitDefaultValue=false)]
        public List<EdiFabricCoreModelEdiX12GE> GeTrailers { get; set; }

        /// <summary>
        /// Gets or Sets Transactions
        /// </summary>
        [DataMember(Name="transactions", EmitDefaultValue=false)]
        public List<EdiFabricCoreModelEdiEdiMessage> Transactions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EdiFabricWebApiModelsX12Group {\n");
            sb.Append("  Gs: ").Append(Gs).Append("\n");
            sb.Append("  GeTrailers: ").Append(GeTrailers).Append("\n");
            sb.Append("  Transactions: ").Append(Transactions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EdiFabricWebApiModelsX12Group);
        }

        /// <summary>
        /// Returns true if EdiFabricWebApiModelsX12Group instances are equal
        /// </summary>
        /// <param name="input">Instance of EdiFabricWebApiModelsX12Group to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EdiFabricWebApiModelsX12Group input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Gs == input.Gs ||
                    (this.Gs != null &&
                    this.Gs.Equals(input.Gs))
                ) && 
                (
                    this.GeTrailers == input.GeTrailers ||
                    this.GeTrailers != null &&
                    this.GeTrailers.SequenceEqual(input.GeTrailers)
                ) && 
                (
                    this.Transactions == input.Transactions ||
                    this.Transactions != null &&
                    this.Transactions.SequenceEqual(input.Transactions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Gs != null)
                    hashCode = hashCode * 59 + this.Gs.GetHashCode();
                if (this.GeTrailers != null)
                    hashCode = hashCode * 59 + this.GeTrailers.GetHashCode();
                if (this.Transactions != null)
                    hashCode = hashCode * 59 + this.Transactions.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
