/* 
 * EdiFabric API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// EdiFabricCoreModelEdiErrorContextsMessageErrorContext
    /// </summary>
    [DataContract]
    public partial class EdiFabricCoreModelEdiErrorContextsMessageErrorContext :  IEquatable<EdiFabricCoreModelEdiErrorContextsMessageErrorContext>, IValidatableObject
    {
        /// <summary>
        /// Defines Codes
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CodesEnum
        {
            
            /// <summary>
            /// Enum TransactionSetNotSupported for value: TransactionSetNotSupported
            /// </summary>
            [EnumMember(Value = "TransactionSetNotSupported")]
            TransactionSetNotSupported = 1,
            
            /// <summary>
            /// Enum MessageTrailerMissing for value: MessageTrailerMissing
            /// </summary>
            [EnumMember(Value = "MessageTrailerMissing")]
            MessageTrailerMissing = 2,
            
            /// <summary>
            /// Enum ControlNumberNotMatching for value: ControlNumberNotMatching
            /// </summary>
            [EnumMember(Value = "ControlNumberNotMatching")]
            ControlNumberNotMatching = 3,
            
            /// <summary>
            /// Enum SegmentsCountNotMatching for value: SegmentsCountNotMatching
            /// </summary>
            [EnumMember(Value = "SegmentsCountNotMatching")]
            SegmentsCountNotMatching = 4,
            
            /// <summary>
            /// Enum MessageWithErrors for value: MessageWithErrors
            /// </summary>
            [EnumMember(Value = "MessageWithErrors")]
            MessageWithErrors = 5,
            
            /// <summary>
            /// Enum MissingOrInvalidTransactionSet for value: MissingOrInvalidTransactionSet
            /// </summary>
            [EnumMember(Value = "MissingOrInvalidTransactionSet")]
            MissingOrInvalidTransactionSet = 6,
            
            /// <summary>
            /// Enum MissingOrInvalidControlNumber for value: MissingOrInvalidControlNumber
            /// </summary>
            [EnumMember(Value = "MissingOrInvalidControlNumber")]
            MissingOrInvalidControlNumber = 7,
            
            /// <summary>
            /// Enum DuplicateMessageControlNumber for value: DuplicateMessageControlNumber
            /// </summary>
            [EnumMember(Value = "DuplicateMessageControlNumber")]
            DuplicateMessageControlNumber = 8,
            
            /// <summary>
            /// Enum FunctionalGroupVersionNotSupported for value: FunctionalGroupVersionNotSupported
            /// </summary>
            [EnumMember(Value = "FunctionalGroupVersionNotSupported")]
            FunctionalGroupVersionNotSupported = 9
        }


        /// <summary>
        /// Gets or Sets Codes
        /// </summary>
        [DataMember(Name="codes", EmitDefaultValue=false)]
        public List<CodesEnum> Codes { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EdiFabricCoreModelEdiErrorContextsMessageErrorContext" /> class.
        /// </summary>
        /// <param name="name">name.</param>
        /// <param name="controlNumber">controlNumber.</param>
        /// <param name="version">version.</param>
        /// <param name="codes">codes.</param>
        /// <param name="errors">errors.</param>
        /// <param name="hasErrors">hasErrors.</param>
        /// <param name="message">message.</param>
        public EdiFabricCoreModelEdiErrorContextsMessageErrorContext(string name = default(string), string controlNumber = default(string), string version = default(string), List<CodesEnum> codes = default(List<CodesEnum>), List<EdiFabricCoreModelEdiErrorContextsSegmentErrorContext> errors = default(List<EdiFabricCoreModelEdiErrorContextsSegmentErrorContext>), bool? hasErrors = default(bool?), string message = default(string))
        {
            this.Name = name;
            this.ControlNumber = controlNumber;
            this.Version = version;
            this.Codes = codes;
            this.Errors = errors;
            this.HasErrors = hasErrors;
            this.Message = message;
        }
        
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets ControlNumber
        /// </summary>
        [DataMember(Name="controlNumber", EmitDefaultValue=false)]
        public string ControlNumber { get; set; }

        /// <summary>
        /// Gets or Sets Version
        /// </summary>
        [DataMember(Name="version", EmitDefaultValue=false)]
        public string Version { get; set; }


        /// <summary>
        /// Gets or Sets Errors
        /// </summary>
        [DataMember(Name="errors", EmitDefaultValue=false)]
        public List<EdiFabricCoreModelEdiErrorContextsSegmentErrorContext> Errors { get; set; }

        /// <summary>
        /// Gets or Sets HasErrors
        /// </summary>
        [DataMember(Name="hasErrors", EmitDefaultValue=false)]
        public bool? HasErrors { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name="message", EmitDefaultValue=false)]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EdiFabricCoreModelEdiErrorContextsMessageErrorContext {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ControlNumber: ").Append(ControlNumber).Append("\n");
            sb.Append("  Version: ").Append(Version).Append("\n");
            sb.Append("  Codes: ").Append(Codes).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("  HasErrors: ").Append(HasErrors).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EdiFabricCoreModelEdiErrorContextsMessageErrorContext);
        }

        /// <summary>
        /// Returns true if EdiFabricCoreModelEdiErrorContextsMessageErrorContext instances are equal
        /// </summary>
        /// <param name="input">Instance of EdiFabricCoreModelEdiErrorContextsMessageErrorContext to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EdiFabricCoreModelEdiErrorContextsMessageErrorContext input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.ControlNumber == input.ControlNumber ||
                    (this.ControlNumber != null &&
                    this.ControlNumber.Equals(input.ControlNumber))
                ) && 
                (
                    this.Version == input.Version ||
                    (this.Version != null &&
                    this.Version.Equals(input.Version))
                ) && 
                (
                    this.Codes == input.Codes ||
                    this.Codes != null &&
                    this.Codes.SequenceEqual(input.Codes)
                ) && 
                (
                    this.Errors == input.Errors ||
                    this.Errors != null &&
                    this.Errors.SequenceEqual(input.Errors)
                ) && 
                (
                    this.HasErrors == input.HasErrors ||
                    (this.HasErrors != null &&
                    this.HasErrors.Equals(input.HasErrors))
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.ControlNumber != null)
                    hashCode = hashCode * 59 + this.ControlNumber.GetHashCode();
                if (this.Version != null)
                    hashCode = hashCode * 59 + this.Version.GetHashCode();
                if (this.Codes != null)
                    hashCode = hashCode * 59 + this.Codes.GetHashCode();
                if (this.Errors != null)
                    hashCode = hashCode * 59 + this.Errors.GetHashCode();
                if (this.HasErrors != null)
                    hashCode = hashCode * 59 + this.HasErrors.GetHashCode();
                if (this.Message != null)
                    hashCode = hashCode * 59 + this.Message.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
