/* 
 * EdiFabric API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// EdiFabricCoreModelEdiEdifactS005
    /// </summary>
    [DataContract]
    public partial class EdiFabricCoreModelEdiEdifactS005 :  IEquatable<EdiFabricCoreModelEdiEdifactS005>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdiFabricCoreModelEdiEdifactS005" /> class.
        /// </summary>
        /// <param name="recipientReferencePassword1">recipientReferencePassword1.</param>
        /// <param name="recipientReferencePasswordQualifier2">recipientReferencePasswordQualifier2.</param>
        public EdiFabricCoreModelEdiEdifactS005(string recipientReferencePassword1 = default(string), string recipientReferencePasswordQualifier2 = default(string))
        {
            this.RecipientReferencePassword1 = recipientReferencePassword1;
            this.RecipientReferencePasswordQualifier2 = recipientReferencePasswordQualifier2;
        }
        
        /// <summary>
        /// Gets or Sets RecipientReferencePassword1
        /// </summary>
        [DataMember(Name="recipientReferencePassword_1", EmitDefaultValue=false)]
        public string RecipientReferencePassword1 { get; set; }

        /// <summary>
        /// Gets or Sets RecipientReferencePasswordQualifier2
        /// </summary>
        [DataMember(Name="recipientReferencePasswordQualifier_2", EmitDefaultValue=false)]
        public string RecipientReferencePasswordQualifier2 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EdiFabricCoreModelEdiEdifactS005 {\n");
            sb.Append("  RecipientReferencePassword1: ").Append(RecipientReferencePassword1).Append("\n");
            sb.Append("  RecipientReferencePasswordQualifier2: ").Append(RecipientReferencePasswordQualifier2).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EdiFabricCoreModelEdiEdifactS005);
        }

        /// <summary>
        /// Returns true if EdiFabricCoreModelEdiEdifactS005 instances are equal
        /// </summary>
        /// <param name="input">Instance of EdiFabricCoreModelEdiEdifactS005 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EdiFabricCoreModelEdiEdifactS005 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.RecipientReferencePassword1 == input.RecipientReferencePassword1 ||
                    (this.RecipientReferencePassword1 != null &&
                    this.RecipientReferencePassword1.Equals(input.RecipientReferencePassword1))
                ) && 
                (
                    this.RecipientReferencePasswordQualifier2 == input.RecipientReferencePasswordQualifier2 ||
                    (this.RecipientReferencePasswordQualifier2 != null &&
                    this.RecipientReferencePasswordQualifier2.Equals(input.RecipientReferencePasswordQualifier2))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RecipientReferencePassword1 != null)
                    hashCode = hashCode * 59 + this.RecipientReferencePassword1.GetHashCode();
                if (this.RecipientReferencePasswordQualifier2 != null)
                    hashCode = hashCode * 59 + this.RecipientReferencePasswordQualifier2.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
