<?php
/**
 * GenerateApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EdiFabric API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.4
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * GenerateApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GenerateApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for generateEdifactGroup
     *
     * .
     *
     */
    public function testGenerateEdifactGroup()
    {
    }

    /**
     * Test case for generateEdifactInterchange
     *
     * .
     *
     */
    public function testGenerateEdifactInterchange()
    {
    }

    /**
     * Test case for generateEdifactTransactions
     *
     * .
     *
     */
    public function testGenerateEdifactTransactions()
    {
    }

    /**
     * Test case for generateGs
     *
     * .
     *
     */
    public function testGenerateGs()
    {
    }

    /**
     * Test case for generateIsa
     *
     * .
     *
     */
    public function testGenerateIsa()
    {
    }

    /**
     * Test case for generateUnb
     *
     * .
     *
     */
    public function testGenerateUnb()
    {
    }

    /**
     * Test case for generateUng
     *
     * .
     *
     */
    public function testGenerateUng()
    {
    }

    /**
     * Test case for generateX12Group
     *
     * .
     *
     */
    public function testGenerateX12Group()
    {
    }

    /**
     * Test case for generateX12Interchange
     *
     * .
     *
     */
    public function testGenerateX12Interchange()
    {
    }

    /**
     * Test case for generateX12Transactions
     *
     * .
     *
     */
    public function testGenerateX12Transactions()
    {
    }
}
