/*
 * EdiFabric API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.EdiFabricWebApiModelsEdifactAcknowledgment;
import io.swagger.client.model.EdiFabricWebApiModelsErrorDetails;
import io.swagger.client.model.EdiFabricWebApiModelsX12Acknowledgment;
import java.io.File;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AcknowledgeApi
 */
@Ignore
public class AcknowledgeApiTest {

    private final AcknowledgeApi api = new AcknowledgeApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void acknowledgeEdifactTest() throws ApiException {
        File ediFile = null;
        String readMode = null;
        String accept = null;
        String charSet = null;
        Boolean continueOnError = null;
        Boolean skipTrailerValidation = null;
        String decimalPoint = null;
        String syntaxSet = null;
        Boolean transactionDuplicate = null;
        Boolean groupDuplicate = null;
        String technicalAck = null;
        Boolean generateForValidTransactions = null;
        Boolean allowPartial = null;
        Integer transactionControlNumber = null;
        String eancomSyntax = null;
        Boolean includeTransactions = null;
        List<EdiFabricWebApiModelsEdifactAcknowledgment> response = api.acknowledgeEdifact(ediFile, readMode, accept, charSet, continueOnError, skipTrailerValidation, decimalPoint, syntaxSet, transactionDuplicate, groupDuplicate, technicalAck, generateForValidTransactions, allowPartial, transactionControlNumber, eancomSyntax, includeTransactions);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void acknowledgeX12Test() throws ApiException {
        File ediFile = null;
        String readMode = null;
        String accept = null;
        String charSet = null;
        Boolean continueOnError = null;
        Boolean skipTrailerValidation = null;
        String syntaxSet = null;
        Boolean transactionDuplicate = null;
        Boolean groupDuplicate = null;
        String technicalAck = null;
        Boolean generateForValidTransactions = null;
        Boolean allowPartial = null;
        Integer transactionControlNumber = null;
        String ak901 = null;
        String ackVersion = null;
        Boolean includeTransactions = null;
        List<EdiFabricWebApiModelsX12Acknowledgment> response = api.acknowledgeX12(ediFile, readMode, accept, charSet, continueOnError, skipTrailerValidation, syntaxSet, transactionDuplicate, groupDuplicate, technicalAck, generateForValidTransactions, allowPartial, transactionControlNumber, ak901, ackVersion, includeTransactions);

        // TODO: test validations
    }
    
}
