=begin
#EdiFabric API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.4

=end

require 'date'

module SwaggerClient
  class EdiFabricCoreModelEdiX12GS
    attr_accessor :code_identifying_information_type_1

    attr_accessor :sender_id_code_2

    attr_accessor :receiver_id_code_3

    attr_accessor :date_4

    attr_accessor :time_5

    attr_accessor :group_control_number_6

    attr_accessor :transaction_type_code_7

    attr_accessor :version_and_release_8

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'code_identifying_information_type_1' => :'codeIdentifyingInformationType_1',
        :'sender_id_code_2' => :'senderIDCode_2',
        :'receiver_id_code_3' => :'receiverIDCode_3',
        :'date_4' => :'date_4',
        :'time_5' => :'time_5',
        :'group_control_number_6' => :'groupControlNumber_6',
        :'transaction_type_code_7' => :'transactionTypeCode_7',
        :'version_and_release_8' => :'versionAndRelease_8'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'code_identifying_information_type_1' => :'String',
        :'sender_id_code_2' => :'String',
        :'receiver_id_code_3' => :'String',
        :'date_4' => :'String',
        :'time_5' => :'String',
        :'group_control_number_6' => :'String',
        :'transaction_type_code_7' => :'String',
        :'version_and_release_8' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'codeIdentifyingInformationType_1')
        self.code_identifying_information_type_1 = attributes[:'codeIdentifyingInformationType_1']
      end

      if attributes.has_key?(:'senderIDCode_2')
        self.sender_id_code_2 = attributes[:'senderIDCode_2']
      end

      if attributes.has_key?(:'receiverIDCode_3')
        self.receiver_id_code_3 = attributes[:'receiverIDCode_3']
      end

      if attributes.has_key?(:'date_4')
        self.date_4 = attributes[:'date_4']
      end

      if attributes.has_key?(:'time_5')
        self.time_5 = attributes[:'time_5']
      end

      if attributes.has_key?(:'groupControlNumber_6')
        self.group_control_number_6 = attributes[:'groupControlNumber_6']
      end

      if attributes.has_key?(:'transactionTypeCode_7')
        self.transaction_type_code_7 = attributes[:'transactionTypeCode_7']
      end

      if attributes.has_key?(:'versionAndRelease_8')
        self.version_and_release_8 = attributes[:'versionAndRelease_8']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          code_identifying_information_type_1 == o.code_identifying_information_type_1 &&
          sender_id_code_2 == o.sender_id_code_2 &&
          receiver_id_code_3 == o.receiver_id_code_3 &&
          date_4 == o.date_4 &&
          time_5 == o.time_5 &&
          group_control_number_6 == o.group_control_number_6 &&
          transaction_type_code_7 == o.transaction_type_code_7 &&
          version_and_release_8 == o.version_and_release_8
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [code_identifying_information_type_1, sender_id_code_2, receiver_id_code_3, date_4, time_5, group_control_number_6, transaction_type_code_7, version_and_release_8].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
