<?php
/**
 * AcknowledgeApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EdiFabric API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.4
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * AcknowledgeApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AcknowledgeApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation acknowledgeEdifact
     *
     * @param  \SplFileObject $edi_file EDI file to translate (required)
     * @param  string $read_mode read_mode (optional, default to read_small)
     * @param  string $accept accept (optional, default to application/json)
     * @param  string $char_set char_set (optional, default to utf-8)
     * @param  bool $continue_on_error continue_on_error (optional, default to true)
     * @param  bool $skip_trailer_validation skip_trailer_validation (optional, default to false)
     * @param  string $decimal_point decimal_point (optional, default to .)
     * @param  string $syntax_set syntax_set (optional)
     * @param  bool $transaction_duplicate transaction_duplicate (optional, default to false)
     * @param  bool $group_duplicate group_duplicate (optional, default to false)
     * @param  string $technical_ack technical_ack (optional, default to default)
     * @param  bool $generate_for_valid_transactions generate_for_valid_transactions (optional, default to false)
     * @param  bool $allow_partial allow_partial (optional, default to false)
     * @param  int $transaction_control_number transaction_control_number (optional, default to 1)
     * @param  string $eancom_syntax eancom_syntax (optional)
     * @param  bool $include_transactions include_transactions (optional, default to false)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\EdiFabricWebApiModelsEdifactAcknowledgment[]
     */
    public function acknowledgeEdifact($edi_file, $read_mode = 'read_small', $accept = 'application/json', $char_set = 'utf-8', $continue_on_error = 'true', $skip_trailer_validation = 'false', $decimal_point = '.', $syntax_set = null, $transaction_duplicate = 'false', $group_duplicate = 'false', $technical_ack = 'default', $generate_for_valid_transactions = 'false', $allow_partial = 'false', $transaction_control_number = '1', $eancom_syntax = null, $include_transactions = 'false')
    {
        list($response) = $this->acknowledgeEdifactWithHttpInfo($edi_file, $read_mode, $accept, $char_set, $continue_on_error, $skip_trailer_validation, $decimal_point, $syntax_set, $transaction_duplicate, $group_duplicate, $technical_ack, $generate_for_valid_transactions, $allow_partial, $transaction_control_number, $eancom_syntax, $include_transactions);
        return $response;
    }

    /**
     * Operation acknowledgeEdifactWithHttpInfo
     *
     * @param  \SplFileObject $edi_file EDI file to translate (required)
     * @param  string $read_mode (optional, default to read_small)
     * @param  string $accept (optional, default to application/json)
     * @param  string $char_set (optional, default to utf-8)
     * @param  bool $continue_on_error (optional, default to true)
     * @param  bool $skip_trailer_validation (optional, default to false)
     * @param  string $decimal_point (optional, default to .)
     * @param  string $syntax_set (optional)
     * @param  bool $transaction_duplicate (optional, default to false)
     * @param  bool $group_duplicate (optional, default to false)
     * @param  string $technical_ack (optional, default to default)
     * @param  bool $generate_for_valid_transactions (optional, default to false)
     * @param  bool $allow_partial (optional, default to false)
     * @param  int $transaction_control_number (optional, default to 1)
     * @param  string $eancom_syntax (optional)
     * @param  bool $include_transactions (optional, default to false)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\EdiFabricWebApiModelsEdifactAcknowledgment[], HTTP status code, HTTP response headers (array of strings)
     */
    public function acknowledgeEdifactWithHttpInfo($edi_file, $read_mode = 'read_small', $accept = 'application/json', $char_set = 'utf-8', $continue_on_error = 'true', $skip_trailer_validation = 'false', $decimal_point = '.', $syntax_set = null, $transaction_duplicate = 'false', $group_duplicate = 'false', $technical_ack = 'default', $generate_for_valid_transactions = 'false', $allow_partial = 'false', $transaction_control_number = '1', $eancom_syntax = null, $include_transactions = 'false')
    {
        $returnType = '\Swagger\Client\Model\EdiFabricWebApiModelsEdifactAcknowledgment[]';
        $request = $this->acknowledgeEdifactRequest($edi_file, $read_mode, $accept, $char_set, $continue_on_error, $skip_trailer_validation, $decimal_point, $syntax_set, $transaction_duplicate, $group_duplicate, $technical_ack, $generate_for_valid_transactions, $allow_partial, $transaction_control_number, $eancom_syntax, $include_transactions);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\EdiFabricWebApiModelsEdifactAcknowledgment[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\EdiFabricWebApiModelsErrorDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\EdiFabricWebApiModelsErrorDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation acknowledgeEdifactAsync
     *
     * 
     *
     * @param  \SplFileObject $edi_file EDI file to translate (required)
     * @param  string $read_mode (optional, default to read_small)
     * @param  string $accept (optional, default to application/json)
     * @param  string $char_set (optional, default to utf-8)
     * @param  bool $continue_on_error (optional, default to true)
     * @param  bool $skip_trailer_validation (optional, default to false)
     * @param  string $decimal_point (optional, default to .)
     * @param  string $syntax_set (optional)
     * @param  bool $transaction_duplicate (optional, default to false)
     * @param  bool $group_duplicate (optional, default to false)
     * @param  string $technical_ack (optional, default to default)
     * @param  bool $generate_for_valid_transactions (optional, default to false)
     * @param  bool $allow_partial (optional, default to false)
     * @param  int $transaction_control_number (optional, default to 1)
     * @param  string $eancom_syntax (optional)
     * @param  bool $include_transactions (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function acknowledgeEdifactAsync($edi_file, $read_mode = 'read_small', $accept = 'application/json', $char_set = 'utf-8', $continue_on_error = 'true', $skip_trailer_validation = 'false', $decimal_point = '.', $syntax_set = null, $transaction_duplicate = 'false', $group_duplicate = 'false', $technical_ack = 'default', $generate_for_valid_transactions = 'false', $allow_partial = 'false', $transaction_control_number = '1', $eancom_syntax = null, $include_transactions = 'false')
    {
        return $this->acknowledgeEdifactAsyncWithHttpInfo($edi_file, $read_mode, $accept, $char_set, $continue_on_error, $skip_trailer_validation, $decimal_point, $syntax_set, $transaction_duplicate, $group_duplicate, $technical_ack, $generate_for_valid_transactions, $allow_partial, $transaction_control_number, $eancom_syntax, $include_transactions)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation acknowledgeEdifactAsyncWithHttpInfo
     *
     * 
     *
     * @param  \SplFileObject $edi_file EDI file to translate (required)
     * @param  string $read_mode (optional, default to read_small)
     * @param  string $accept (optional, default to application/json)
     * @param  string $char_set (optional, default to utf-8)
     * @param  bool $continue_on_error (optional, default to true)
     * @param  bool $skip_trailer_validation (optional, default to false)
     * @param  string $decimal_point (optional, default to .)
     * @param  string $syntax_set (optional)
     * @param  bool $transaction_duplicate (optional, default to false)
     * @param  bool $group_duplicate (optional, default to false)
     * @param  string $technical_ack (optional, default to default)
     * @param  bool $generate_for_valid_transactions (optional, default to false)
     * @param  bool $allow_partial (optional, default to false)
     * @param  int $transaction_control_number (optional, default to 1)
     * @param  string $eancom_syntax (optional)
     * @param  bool $include_transactions (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function acknowledgeEdifactAsyncWithHttpInfo($edi_file, $read_mode = 'read_small', $accept = 'application/json', $char_set = 'utf-8', $continue_on_error = 'true', $skip_trailer_validation = 'false', $decimal_point = '.', $syntax_set = null, $transaction_duplicate = 'false', $group_duplicate = 'false', $technical_ack = 'default', $generate_for_valid_transactions = 'false', $allow_partial = 'false', $transaction_control_number = '1', $eancom_syntax = null, $include_transactions = 'false')
    {
        $returnType = '\Swagger\Client\Model\EdiFabricWebApiModelsEdifactAcknowledgment[]';
        $request = $this->acknowledgeEdifactRequest($edi_file, $read_mode, $accept, $char_set, $continue_on_error, $skip_trailer_validation, $decimal_point, $syntax_set, $transaction_duplicate, $group_duplicate, $technical_ack, $generate_for_valid_transactions, $allow_partial, $transaction_control_number, $eancom_syntax, $include_transactions);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'acknowledgeEdifact'
     *
     * @param  \SplFileObject $edi_file EDI file to translate (required)
     * @param  string $read_mode (optional, default to read_small)
     * @param  string $accept (optional, default to application/json)
     * @param  string $char_set (optional, default to utf-8)
     * @param  bool $continue_on_error (optional, default to true)
     * @param  bool $skip_trailer_validation (optional, default to false)
     * @param  string $decimal_point (optional, default to .)
     * @param  string $syntax_set (optional)
     * @param  bool $transaction_duplicate (optional, default to false)
     * @param  bool $group_duplicate (optional, default to false)
     * @param  string $technical_ack (optional, default to default)
     * @param  bool $generate_for_valid_transactions (optional, default to false)
     * @param  bool $allow_partial (optional, default to false)
     * @param  int $transaction_control_number (optional, default to 1)
     * @param  string $eancom_syntax (optional)
     * @param  bool $include_transactions (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function acknowledgeEdifactRequest($edi_file, $read_mode = 'read_small', $accept = 'application/json', $char_set = 'utf-8', $continue_on_error = 'true', $skip_trailer_validation = 'false', $decimal_point = '.', $syntax_set = null, $transaction_duplicate = 'false', $group_duplicate = 'false', $technical_ack = 'default', $generate_for_valid_transactions = 'false', $allow_partial = 'false', $transaction_control_number = '1', $eancom_syntax = null, $include_transactions = 'false')
    {
        // verify the required parameter 'edi_file' is set
        if ($edi_file === null || (is_array($edi_file) && count($edi_file) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $edi_file when calling acknowledgeEdifact'
            );
        }

        $resourcePath = '/acknowledge/edifact';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($read_mode !== null) {
            $queryParams['read_mode'] = ObjectSerializer::toQueryValue($read_mode);
        }
        // header params
        if ($accept !== null) {
            $headerParams['Accept'] = ObjectSerializer::toHeaderValue($accept);
        }


        // form params
        if ($char_set !== null) {
            $formParams['char_set'] = ObjectSerializer::toFormValue($char_set);
        }
        // form params
        if ($continue_on_error !== null) {
            $formParams['continue_on_error'] = ObjectSerializer::toFormValue($continue_on_error);
        }
        // form params
        if ($skip_trailer_validation !== null) {
            $formParams['skip_trailer_validation'] = ObjectSerializer::toFormValue($skip_trailer_validation);
        }
        // form params
        if ($decimal_point !== null) {
            $formParams['decimal_point'] = ObjectSerializer::toFormValue($decimal_point);
        }
        // form params
        if ($syntax_set !== null) {
            $formParams['syntax_set'] = ObjectSerializer::toFormValue($syntax_set);
        }
        // form params
        if ($transaction_duplicate !== null) {
            $formParams['transaction_duplicate'] = ObjectSerializer::toFormValue($transaction_duplicate);
        }
        // form params
        if ($group_duplicate !== null) {
            $formParams['group_duplicate'] = ObjectSerializer::toFormValue($group_duplicate);
        }
        // form params
        if ($technical_ack !== null) {
            $formParams['technical_ack'] = ObjectSerializer::toFormValue($technical_ack);
        }
        // form params
        if ($generate_for_valid_transactions !== null) {
            $formParams['generate_for_valid_transactions'] = ObjectSerializer::toFormValue($generate_for_valid_transactions);
        }
        // form params
        if ($allow_partial !== null) {
            $formParams['allow_partial'] = ObjectSerializer::toFormValue($allow_partial);
        }
        // form params
        if ($transaction_control_number !== null) {
            $formParams['transaction_control_number'] = ObjectSerializer::toFormValue($transaction_control_number);
        }
        // form params
        if ($eancom_syntax !== null) {
            $formParams['eancom_syntax'] = ObjectSerializer::toFormValue($eancom_syntax);
        }
        // form params
        if ($include_transactions !== null) {
            $formParams['include_transactions'] = ObjectSerializer::toFormValue($include_transactions);
        }
        // form params
        if ($edi_file !== null) {
            $multipart = true;
            $formParams['edi_file'] = \GuzzleHttp\Psr7\try_fopen(ObjectSerializer::toFormValue($edi_file), 'rb');
        }
        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'application/xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'application/xml'],
                ['multipart/form-data']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation acknowledgeX12
     *
     * @param  \SplFileObject $edi_file EDI file to translate (required)
     * @param  string $read_mode read_mode (optional, default to read_small)
     * @param  string $accept accept (optional, default to application/json)
     * @param  string $char_set char_set (optional, default to utf-8)
     * @param  bool $continue_on_error continue_on_error (optional, default to true)
     * @param  bool $skip_trailer_validation skip_trailer_validation (optional, default to false)
     * @param  string $syntax_set syntax_set (optional)
     * @param  bool $transaction_duplicate transaction_duplicate (optional, default to false)
     * @param  bool $group_duplicate group_duplicate (optional, default to false)
     * @param  string $technical_ack technical_ack (optional, default to default)
     * @param  bool $generate_for_valid_transactions generate_for_valid_transactions (optional, default to false)
     * @param  bool $allow_partial allow_partial (optional, default to false)
     * @param  int $transaction_control_number transaction_control_number (optional, default to 1)
     * @param  string $ak901 ak901 (optional, default to e)
     * @param  string $ack_version ack_version (optional, default to 4010_997)
     * @param  bool $include_transactions include_transactions (optional, default to false)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\EdiFabricWebApiModelsX12Acknowledgment[]
     */
    public function acknowledgeX12($edi_file, $read_mode = 'read_small', $accept = 'application/json', $char_set = 'utf-8', $continue_on_error = 'true', $skip_trailer_validation = 'false', $syntax_set = null, $transaction_duplicate = 'false', $group_duplicate = 'false', $technical_ack = 'default', $generate_for_valid_transactions = 'false', $allow_partial = 'false', $transaction_control_number = '1', $ak901 = 'e', $ack_version = '4010_997', $include_transactions = 'false')
    {
        list($response) = $this->acknowledgeX12WithHttpInfo($edi_file, $read_mode, $accept, $char_set, $continue_on_error, $skip_trailer_validation, $syntax_set, $transaction_duplicate, $group_duplicate, $technical_ack, $generate_for_valid_transactions, $allow_partial, $transaction_control_number, $ak901, $ack_version, $include_transactions);
        return $response;
    }

    /**
     * Operation acknowledgeX12WithHttpInfo
     *
     * @param  \SplFileObject $edi_file EDI file to translate (required)
     * @param  string $read_mode (optional, default to read_small)
     * @param  string $accept (optional, default to application/json)
     * @param  string $char_set (optional, default to utf-8)
     * @param  bool $continue_on_error (optional, default to true)
     * @param  bool $skip_trailer_validation (optional, default to false)
     * @param  string $syntax_set (optional)
     * @param  bool $transaction_duplicate (optional, default to false)
     * @param  bool $group_duplicate (optional, default to false)
     * @param  string $technical_ack (optional, default to default)
     * @param  bool $generate_for_valid_transactions (optional, default to false)
     * @param  bool $allow_partial (optional, default to false)
     * @param  int $transaction_control_number (optional, default to 1)
     * @param  string $ak901 (optional, default to e)
     * @param  string $ack_version (optional, default to 4010_997)
     * @param  bool $include_transactions (optional, default to false)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\EdiFabricWebApiModelsX12Acknowledgment[], HTTP status code, HTTP response headers (array of strings)
     */
    public function acknowledgeX12WithHttpInfo($edi_file, $read_mode = 'read_small', $accept = 'application/json', $char_set = 'utf-8', $continue_on_error = 'true', $skip_trailer_validation = 'false', $syntax_set = null, $transaction_duplicate = 'false', $group_duplicate = 'false', $technical_ack = 'default', $generate_for_valid_transactions = 'false', $allow_partial = 'false', $transaction_control_number = '1', $ak901 = 'e', $ack_version = '4010_997', $include_transactions = 'false')
    {
        $returnType = '\Swagger\Client\Model\EdiFabricWebApiModelsX12Acknowledgment[]';
        $request = $this->acknowledgeX12Request($edi_file, $read_mode, $accept, $char_set, $continue_on_error, $skip_trailer_validation, $syntax_set, $transaction_duplicate, $group_duplicate, $technical_ack, $generate_for_valid_transactions, $allow_partial, $transaction_control_number, $ak901, $ack_version, $include_transactions);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\EdiFabricWebApiModelsX12Acknowledgment[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\EdiFabricWebApiModelsErrorDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\EdiFabricWebApiModelsErrorDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation acknowledgeX12Async
     *
     * 
     *
     * @param  \SplFileObject $edi_file EDI file to translate (required)
     * @param  string $read_mode (optional, default to read_small)
     * @param  string $accept (optional, default to application/json)
     * @param  string $char_set (optional, default to utf-8)
     * @param  bool $continue_on_error (optional, default to true)
     * @param  bool $skip_trailer_validation (optional, default to false)
     * @param  string $syntax_set (optional)
     * @param  bool $transaction_duplicate (optional, default to false)
     * @param  bool $group_duplicate (optional, default to false)
     * @param  string $technical_ack (optional, default to default)
     * @param  bool $generate_for_valid_transactions (optional, default to false)
     * @param  bool $allow_partial (optional, default to false)
     * @param  int $transaction_control_number (optional, default to 1)
     * @param  string $ak901 (optional, default to e)
     * @param  string $ack_version (optional, default to 4010_997)
     * @param  bool $include_transactions (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function acknowledgeX12Async($edi_file, $read_mode = 'read_small', $accept = 'application/json', $char_set = 'utf-8', $continue_on_error = 'true', $skip_trailer_validation = 'false', $syntax_set = null, $transaction_duplicate = 'false', $group_duplicate = 'false', $technical_ack = 'default', $generate_for_valid_transactions = 'false', $allow_partial = 'false', $transaction_control_number = '1', $ak901 = 'e', $ack_version = '4010_997', $include_transactions = 'false')
    {
        return $this->acknowledgeX12AsyncWithHttpInfo($edi_file, $read_mode, $accept, $char_set, $continue_on_error, $skip_trailer_validation, $syntax_set, $transaction_duplicate, $group_duplicate, $technical_ack, $generate_for_valid_transactions, $allow_partial, $transaction_control_number, $ak901, $ack_version, $include_transactions)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation acknowledgeX12AsyncWithHttpInfo
     *
     * 
     *
     * @param  \SplFileObject $edi_file EDI file to translate (required)
     * @param  string $read_mode (optional, default to read_small)
     * @param  string $accept (optional, default to application/json)
     * @param  string $char_set (optional, default to utf-8)
     * @param  bool $continue_on_error (optional, default to true)
     * @param  bool $skip_trailer_validation (optional, default to false)
     * @param  string $syntax_set (optional)
     * @param  bool $transaction_duplicate (optional, default to false)
     * @param  bool $group_duplicate (optional, default to false)
     * @param  string $technical_ack (optional, default to default)
     * @param  bool $generate_for_valid_transactions (optional, default to false)
     * @param  bool $allow_partial (optional, default to false)
     * @param  int $transaction_control_number (optional, default to 1)
     * @param  string $ak901 (optional, default to e)
     * @param  string $ack_version (optional, default to 4010_997)
     * @param  bool $include_transactions (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function acknowledgeX12AsyncWithHttpInfo($edi_file, $read_mode = 'read_small', $accept = 'application/json', $char_set = 'utf-8', $continue_on_error = 'true', $skip_trailer_validation = 'false', $syntax_set = null, $transaction_duplicate = 'false', $group_duplicate = 'false', $technical_ack = 'default', $generate_for_valid_transactions = 'false', $allow_partial = 'false', $transaction_control_number = '1', $ak901 = 'e', $ack_version = '4010_997', $include_transactions = 'false')
    {
        $returnType = '\Swagger\Client\Model\EdiFabricWebApiModelsX12Acknowledgment[]';
        $request = $this->acknowledgeX12Request($edi_file, $read_mode, $accept, $char_set, $continue_on_error, $skip_trailer_validation, $syntax_set, $transaction_duplicate, $group_duplicate, $technical_ack, $generate_for_valid_transactions, $allow_partial, $transaction_control_number, $ak901, $ack_version, $include_transactions);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'acknowledgeX12'
     *
     * @param  \SplFileObject $edi_file EDI file to translate (required)
     * @param  string $read_mode (optional, default to read_small)
     * @param  string $accept (optional, default to application/json)
     * @param  string $char_set (optional, default to utf-8)
     * @param  bool $continue_on_error (optional, default to true)
     * @param  bool $skip_trailer_validation (optional, default to false)
     * @param  string $syntax_set (optional)
     * @param  bool $transaction_duplicate (optional, default to false)
     * @param  bool $group_duplicate (optional, default to false)
     * @param  string $technical_ack (optional, default to default)
     * @param  bool $generate_for_valid_transactions (optional, default to false)
     * @param  bool $allow_partial (optional, default to false)
     * @param  int $transaction_control_number (optional, default to 1)
     * @param  string $ak901 (optional, default to e)
     * @param  string $ack_version (optional, default to 4010_997)
     * @param  bool $include_transactions (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function acknowledgeX12Request($edi_file, $read_mode = 'read_small', $accept = 'application/json', $char_set = 'utf-8', $continue_on_error = 'true', $skip_trailer_validation = 'false', $syntax_set = null, $transaction_duplicate = 'false', $group_duplicate = 'false', $technical_ack = 'default', $generate_for_valid_transactions = 'false', $allow_partial = 'false', $transaction_control_number = '1', $ak901 = 'e', $ack_version = '4010_997', $include_transactions = 'false')
    {
        // verify the required parameter 'edi_file' is set
        if ($edi_file === null || (is_array($edi_file) && count($edi_file) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $edi_file when calling acknowledgeX12'
            );
        }

        $resourcePath = '/acknowledge/x12';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($read_mode !== null) {
            $queryParams['read_mode'] = ObjectSerializer::toQueryValue($read_mode);
        }
        // header params
        if ($accept !== null) {
            $headerParams['Accept'] = ObjectSerializer::toHeaderValue($accept);
        }


        // form params
        if ($char_set !== null) {
            $formParams['char_set'] = ObjectSerializer::toFormValue($char_set);
        }
        // form params
        if ($continue_on_error !== null) {
            $formParams['continue_on_error'] = ObjectSerializer::toFormValue($continue_on_error);
        }
        // form params
        if ($skip_trailer_validation !== null) {
            $formParams['skip_trailer_validation'] = ObjectSerializer::toFormValue($skip_trailer_validation);
        }
        // form params
        if ($syntax_set !== null) {
            $formParams['syntax_set'] = ObjectSerializer::toFormValue($syntax_set);
        }
        // form params
        if ($transaction_duplicate !== null) {
            $formParams['transaction_duplicate'] = ObjectSerializer::toFormValue($transaction_duplicate);
        }
        // form params
        if ($group_duplicate !== null) {
            $formParams['group_duplicate'] = ObjectSerializer::toFormValue($group_duplicate);
        }
        // form params
        if ($technical_ack !== null) {
            $formParams['technical_ack'] = ObjectSerializer::toFormValue($technical_ack);
        }
        // form params
        if ($generate_for_valid_transactions !== null) {
            $formParams['generate_for_valid_transactions'] = ObjectSerializer::toFormValue($generate_for_valid_transactions);
        }
        // form params
        if ($allow_partial !== null) {
            $formParams['allow_partial'] = ObjectSerializer::toFormValue($allow_partial);
        }
        // form params
        if ($transaction_control_number !== null) {
            $formParams['transaction_control_number'] = ObjectSerializer::toFormValue($transaction_control_number);
        }
        // form params
        if ($ak901 !== null) {
            $formParams['ak901'] = ObjectSerializer::toFormValue($ak901);
        }
        // form params
        if ($ack_version !== null) {
            $formParams['ack_version'] = ObjectSerializer::toFormValue($ack_version);
        }
        // form params
        if ($include_transactions !== null) {
            $formParams['include_transactions'] = ObjectSerializer::toFormValue($include_transactions);
        }
        // form params
        if ($edi_file !== null) {
            $multipart = true;
            $formParams['edi_file'] = \GuzzleHttp\Psr7\try_fopen(ObjectSerializer::toFormValue($edi_file), 'rb');
        }
        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'application/xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'application/xml'],
                ['multipart/form-data']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
