/*
 * EdiFabric API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type EdiFabricCoreModelEdiEdifactS001 struct {
	SyntaxIdentifier1 string `json:"syntaxIdentifier_1,omitempty"`
	SyntaxVersionNumber2 string `json:"syntaxVersionNumber_2,omitempty"`
	ServiceCodeListDirectoryVersionNumber3 string `json:"serviceCodeListDirectoryVersionNumber_3,omitempty"`
	CharacterEncoding4 string `json:"characterEncoding_4,omitempty"`
}
