/*
 * EdiFabric API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * EdiFabricCoreModelEdiX12GE
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-24T17:09:45.649Z")
public class EdiFabricCoreModelEdiX12GE {
  @SerializedName("numberOfIncludedSets_1")
  private String numberOfIncludedSets1 = null;

  @SerializedName("groupControlNumber_2")
  private String groupControlNumber2 = null;

  public EdiFabricCoreModelEdiX12GE numberOfIncludedSets1(String numberOfIncludedSets1) {
    this.numberOfIncludedSets1 = numberOfIncludedSets1;
    return this;
  }

   /**
   * Get numberOfIncludedSets1
   * @return numberOfIncludedSets1
  **/
  @ApiModelProperty(value = "")
  public String getNumberOfIncludedSets1() {
    return numberOfIncludedSets1;
  }

  public void setNumberOfIncludedSets1(String numberOfIncludedSets1) {
    this.numberOfIncludedSets1 = numberOfIncludedSets1;
  }

  public EdiFabricCoreModelEdiX12GE groupControlNumber2(String groupControlNumber2) {
    this.groupControlNumber2 = groupControlNumber2;
    return this;
  }

   /**
   * Get groupControlNumber2
   * @return groupControlNumber2
  **/
  @ApiModelProperty(value = "")
  public String getGroupControlNumber2() {
    return groupControlNumber2;
  }

  public void setGroupControlNumber2(String groupControlNumber2) {
    this.groupControlNumber2 = groupControlNumber2;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EdiFabricCoreModelEdiX12GE ediFabricCoreModelEdiX12GE = (EdiFabricCoreModelEdiX12GE) o;
    return Objects.equals(this.numberOfIncludedSets1, ediFabricCoreModelEdiX12GE.numberOfIncludedSets1) &&
        Objects.equals(this.groupControlNumber2, ediFabricCoreModelEdiX12GE.groupControlNumber2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numberOfIncludedSets1, groupControlNumber2);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EdiFabricCoreModelEdiX12GE {\n");
    
    sb.append("    numberOfIncludedSets1: ").append(toIndentedString(numberOfIncludedSets1)).append("\n");
    sb.append("    groupControlNumber2: ").append(toIndentedString(groupControlNumber2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

