/*
 * EdiFabric API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.EdiFabricCoreModelEdiEdifactUNB;
import io.swagger.client.model.EdiFabricCoreModelEdiEdifactUNZ;
import io.swagger.client.model.EdiFabricCoreModelEdiErrorContextsReaderErrorContext;
import io.swagger.client.model.EdiFabricWebApiModelsEdifactGroup;
import io.swagger.client.model.EdiFabricWebApiModelsGenerateSettings;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * EdiFabricWebApiModelsGenerateEdifactInterchange
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-24T17:09:45.649Z")
public class EdiFabricWebApiModelsGenerateEdifactInterchange {
  @SerializedName("settings")
  private EdiFabricWebApiModelsGenerateSettings settings = null;

  @SerializedName("unb")
  private EdiFabricCoreModelEdiEdifactUNB unb = null;

  @SerializedName("groups")
  private List<EdiFabricWebApiModelsEdifactGroup> groups = null;

  @SerializedName("unzTrailers")
  private List<EdiFabricCoreModelEdiEdifactUNZ> unzTrailers = null;

  @SerializedName("errors")
  private List<EdiFabricCoreModelEdiErrorContextsReaderErrorContext> errors = null;

  public EdiFabricWebApiModelsGenerateEdifactInterchange settings(EdiFabricWebApiModelsGenerateSettings settings) {
    this.settings = settings;
    return this;
  }

   /**
   * Get settings
   * @return settings
  **/
  @ApiModelProperty(value = "")
  public EdiFabricWebApiModelsGenerateSettings getSettings() {
    return settings;
  }

  public void setSettings(EdiFabricWebApiModelsGenerateSettings settings) {
    this.settings = settings;
  }

  public EdiFabricWebApiModelsGenerateEdifactInterchange unb(EdiFabricCoreModelEdiEdifactUNB unb) {
    this.unb = unb;
    return this;
  }

   /**
   * Get unb
   * @return unb
  **/
  @ApiModelProperty(value = "")
  public EdiFabricCoreModelEdiEdifactUNB getUnb() {
    return unb;
  }

  public void setUnb(EdiFabricCoreModelEdiEdifactUNB unb) {
    this.unb = unb;
  }

  public EdiFabricWebApiModelsGenerateEdifactInterchange groups(List<EdiFabricWebApiModelsEdifactGroup> groups) {
    this.groups = groups;
    return this;
  }

  public EdiFabricWebApiModelsGenerateEdifactInterchange addGroupsItem(EdiFabricWebApiModelsEdifactGroup groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<EdiFabricWebApiModelsEdifactGroup>();
    }
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * Get groups
   * @return groups
  **/
  @ApiModelProperty(value = "")
  public List<EdiFabricWebApiModelsEdifactGroup> getGroups() {
    return groups;
  }

  public void setGroups(List<EdiFabricWebApiModelsEdifactGroup> groups) {
    this.groups = groups;
  }

  public EdiFabricWebApiModelsGenerateEdifactInterchange unzTrailers(List<EdiFabricCoreModelEdiEdifactUNZ> unzTrailers) {
    this.unzTrailers = unzTrailers;
    return this;
  }

  public EdiFabricWebApiModelsGenerateEdifactInterchange addUnzTrailersItem(EdiFabricCoreModelEdiEdifactUNZ unzTrailersItem) {
    if (this.unzTrailers == null) {
      this.unzTrailers = new ArrayList<EdiFabricCoreModelEdiEdifactUNZ>();
    }
    this.unzTrailers.add(unzTrailersItem);
    return this;
  }

   /**
   * Get unzTrailers
   * @return unzTrailers
  **/
  @ApiModelProperty(value = "")
  public List<EdiFabricCoreModelEdiEdifactUNZ> getUnzTrailers() {
    return unzTrailers;
  }

  public void setUnzTrailers(List<EdiFabricCoreModelEdiEdifactUNZ> unzTrailers) {
    this.unzTrailers = unzTrailers;
  }

  public EdiFabricWebApiModelsGenerateEdifactInterchange errors(List<EdiFabricCoreModelEdiErrorContextsReaderErrorContext> errors) {
    this.errors = errors;
    return this;
  }

  public EdiFabricWebApiModelsGenerateEdifactInterchange addErrorsItem(EdiFabricCoreModelEdiErrorContextsReaderErrorContext errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<EdiFabricCoreModelEdiErrorContextsReaderErrorContext>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  @ApiModelProperty(value = "")
  public List<EdiFabricCoreModelEdiErrorContextsReaderErrorContext> getErrors() {
    return errors;
  }

  public void setErrors(List<EdiFabricCoreModelEdiErrorContextsReaderErrorContext> errors) {
    this.errors = errors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EdiFabricWebApiModelsGenerateEdifactInterchange ediFabricWebApiModelsGenerateEdifactInterchange = (EdiFabricWebApiModelsGenerateEdifactInterchange) o;
    return Objects.equals(this.settings, ediFabricWebApiModelsGenerateEdifactInterchange.settings) &&
        Objects.equals(this.unb, ediFabricWebApiModelsGenerateEdifactInterchange.unb) &&
        Objects.equals(this.groups, ediFabricWebApiModelsGenerateEdifactInterchange.groups) &&
        Objects.equals(this.unzTrailers, ediFabricWebApiModelsGenerateEdifactInterchange.unzTrailers) &&
        Objects.equals(this.errors, ediFabricWebApiModelsGenerateEdifactInterchange.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(settings, unb, groups, unzTrailers, errors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EdiFabricWebApiModelsGenerateEdifactInterchange {\n");
    
    sb.append("    settings: ").append(toIndentedString(settings)).append("\n");
    sb.append("    unb: ").append(toIndentedString(unb)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    unzTrailers: ").append(toIndentedString(unzTrailers)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

