/*
 * EdiFabric API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * EdiFabricCoreModelEdiEdifactS003
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-24T17:09:45.649Z")
public class EdiFabricCoreModelEdiEdifactS003 {
  @SerializedName("interchangeRecipientIdentification_1")
  private String interchangeRecipientIdentification1 = null;

  @SerializedName("identificationCodeQualifier_2")
  private String identificationCodeQualifier2 = null;

  @SerializedName("interchangeRecipientInternalIdentification_3")
  private String interchangeRecipientInternalIdentification3 = null;

  @SerializedName("interchangeRecipientInternalSubIdentification_4")
  private String interchangeRecipientInternalSubIdentification4 = null;

  public EdiFabricCoreModelEdiEdifactS003 interchangeRecipientIdentification1(String interchangeRecipientIdentification1) {
    this.interchangeRecipientIdentification1 = interchangeRecipientIdentification1;
    return this;
  }

   /**
   * Get interchangeRecipientIdentification1
   * @return interchangeRecipientIdentification1
  **/
  @ApiModelProperty(value = "")
  public String getInterchangeRecipientIdentification1() {
    return interchangeRecipientIdentification1;
  }

  public void setInterchangeRecipientIdentification1(String interchangeRecipientIdentification1) {
    this.interchangeRecipientIdentification1 = interchangeRecipientIdentification1;
  }

  public EdiFabricCoreModelEdiEdifactS003 identificationCodeQualifier2(String identificationCodeQualifier2) {
    this.identificationCodeQualifier2 = identificationCodeQualifier2;
    return this;
  }

   /**
   * Get identificationCodeQualifier2
   * @return identificationCodeQualifier2
  **/
  @ApiModelProperty(value = "")
  public String getIdentificationCodeQualifier2() {
    return identificationCodeQualifier2;
  }

  public void setIdentificationCodeQualifier2(String identificationCodeQualifier2) {
    this.identificationCodeQualifier2 = identificationCodeQualifier2;
  }

  public EdiFabricCoreModelEdiEdifactS003 interchangeRecipientInternalIdentification3(String interchangeRecipientInternalIdentification3) {
    this.interchangeRecipientInternalIdentification3 = interchangeRecipientInternalIdentification3;
    return this;
  }

   /**
   * Get interchangeRecipientInternalIdentification3
   * @return interchangeRecipientInternalIdentification3
  **/
  @ApiModelProperty(value = "")
  public String getInterchangeRecipientInternalIdentification3() {
    return interchangeRecipientInternalIdentification3;
  }

  public void setInterchangeRecipientInternalIdentification3(String interchangeRecipientInternalIdentification3) {
    this.interchangeRecipientInternalIdentification3 = interchangeRecipientInternalIdentification3;
  }

  public EdiFabricCoreModelEdiEdifactS003 interchangeRecipientInternalSubIdentification4(String interchangeRecipientInternalSubIdentification4) {
    this.interchangeRecipientInternalSubIdentification4 = interchangeRecipientInternalSubIdentification4;
    return this;
  }

   /**
   * Get interchangeRecipientInternalSubIdentification4
   * @return interchangeRecipientInternalSubIdentification4
  **/
  @ApiModelProperty(value = "")
  public String getInterchangeRecipientInternalSubIdentification4() {
    return interchangeRecipientInternalSubIdentification4;
  }

  public void setInterchangeRecipientInternalSubIdentification4(String interchangeRecipientInternalSubIdentification4) {
    this.interchangeRecipientInternalSubIdentification4 = interchangeRecipientInternalSubIdentification4;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EdiFabricCoreModelEdiEdifactS003 ediFabricCoreModelEdiEdifactS003 = (EdiFabricCoreModelEdiEdifactS003) o;
    return Objects.equals(this.interchangeRecipientIdentification1, ediFabricCoreModelEdiEdifactS003.interchangeRecipientIdentification1) &&
        Objects.equals(this.identificationCodeQualifier2, ediFabricCoreModelEdiEdifactS003.identificationCodeQualifier2) &&
        Objects.equals(this.interchangeRecipientInternalIdentification3, ediFabricCoreModelEdiEdifactS003.interchangeRecipientInternalIdentification3) &&
        Objects.equals(this.interchangeRecipientInternalSubIdentification4, ediFabricCoreModelEdiEdifactS003.interchangeRecipientInternalSubIdentification4);
  }

  @Override
  public int hashCode() {
    return Objects.hash(interchangeRecipientIdentification1, identificationCodeQualifier2, interchangeRecipientInternalIdentification3, interchangeRecipientInternalSubIdentification4);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EdiFabricCoreModelEdiEdifactS003 {\n");
    
    sb.append("    interchangeRecipientIdentification1: ").append(toIndentedString(interchangeRecipientIdentification1)).append("\n");
    sb.append("    identificationCodeQualifier2: ").append(toIndentedString(identificationCodeQualifier2)).append("\n");
    sb.append("    interchangeRecipientInternalIdentification3: ").append(toIndentedString(interchangeRecipientInternalIdentification3)).append("\n");
    sb.append("    interchangeRecipientInternalSubIdentification4: ").append(toIndentedString(interchangeRecipientInternalSubIdentification4)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

