/*
 * EdiFabric API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * EdiFabricCoreModelEdiEdifactS004
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-24T17:09:45.649Z")
public class EdiFabricCoreModelEdiEdifactS004 {
  @SerializedName("date_1")
  private String date1 = null;

  @SerializedName("time_2")
  private String time2 = null;

  public EdiFabricCoreModelEdiEdifactS004 date1(String date1) {
    this.date1 = date1;
    return this;
  }

   /**
   * Get date1
   * @return date1
  **/
  @ApiModelProperty(value = "")
  public String getDate1() {
    return date1;
  }

  public void setDate1(String date1) {
    this.date1 = date1;
  }

  public EdiFabricCoreModelEdiEdifactS004 time2(String time2) {
    this.time2 = time2;
    return this;
  }

   /**
   * Get time2
   * @return time2
  **/
  @ApiModelProperty(value = "")
  public String getTime2() {
    return time2;
  }

  public void setTime2(String time2) {
    this.time2 = time2;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EdiFabricCoreModelEdiEdifactS004 ediFabricCoreModelEdiEdifactS004 = (EdiFabricCoreModelEdiEdifactS004) o;
    return Objects.equals(this.date1, ediFabricCoreModelEdiEdifactS004.date1) &&
        Objects.equals(this.time2, ediFabricCoreModelEdiEdifactS004.time2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date1, time2);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EdiFabricCoreModelEdiEdifactS004 {\n");
    
    sb.append("    date1: ").append(toIndentedString(date1)).append("\n");
    sb.append("    time2: ").append(toIndentedString(time2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

