#import <Foundation/Foundation.h>
#import "SWGEdiFabricWebApiModelsEdifactAcknowledgment.h"
#import "SWGEdiFabricWebApiModelsErrorDetails.h"
#import "SWGEdiFabricWebApiModelsX12Acknowledgment.h"
#import "SWGApi.h"

/**
* EdiFabric API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGAcknowledgeApi: NSObject <SWGApi>

extern NSString* kSWGAcknowledgeApiErrorDomain;
extern NSInteger kSWGAcknowledgeApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 
///
/// @param ediFile EDI file to translate
/// @param readMode  (optional) (default to read_small)
/// @param accept  (optional) (default to application/json)
/// @param charSet  (optional) (default to utf-8)
/// @param continueOnError  (optional) (default to true)
/// @param skipTrailerValidation  (optional) (default to false)
/// @param decimalPoint  (optional) (default to .)
/// @param syntaxSet  (optional)
/// @param transactionDuplicate  (optional) (default to false)
/// @param groupDuplicate  (optional) (default to false)
/// @param technicalAck  (optional) (default to default)
/// @param generateForValidTransactions  (optional) (default to false)
/// @param allowPartial  (optional) (default to false)
/// @param transactionControlNumber  (optional) (default to 1)
/// @param eancomSyntax  (optional)
/// @param includeTransactions  (optional) (default to false)
/// 
///  code:200 message:"Success",
///  code:400 message:"Bad Request",
///  code:500 message:"Server Error"
///
/// @return NSArray<SWGEdiFabricWebApiModelsEdifactAcknowledgment>*
-(NSURLSessionTask*) acknowledgeEdifactWithEdiFile: (NSURL*) ediFile
    readMode: (NSString*) readMode
    accept: (NSString*) accept
    charSet: (NSString*) charSet
    continueOnError: (NSNumber*) continueOnError
    skipTrailerValidation: (NSNumber*) skipTrailerValidation
    decimalPoint: (NSString*) decimalPoint
    syntaxSet: (NSString*) syntaxSet
    transactionDuplicate: (NSNumber*) transactionDuplicate
    groupDuplicate: (NSNumber*) groupDuplicate
    technicalAck: (NSString*) technicalAck
    generateForValidTransactions: (NSNumber*) generateForValidTransactions
    allowPartial: (NSNumber*) allowPartial
    transactionControlNumber: (NSNumber*) transactionControlNumber
    eancomSyntax: (NSString*) eancomSyntax
    includeTransactions: (NSNumber*) includeTransactions
    completionHandler: (void (^)(NSArray<SWGEdiFabricWebApiModelsEdifactAcknowledgment>* output, NSError* error)) handler;


/// 
/// 
///
/// @param ediFile EDI file to translate
/// @param readMode  (optional) (default to read_small)
/// @param accept  (optional) (default to application/json)
/// @param charSet  (optional) (default to utf-8)
/// @param continueOnError  (optional) (default to true)
/// @param skipTrailerValidation  (optional) (default to false)
/// @param syntaxSet  (optional)
/// @param transactionDuplicate  (optional) (default to false)
/// @param groupDuplicate  (optional) (default to false)
/// @param technicalAck  (optional) (default to default)
/// @param generateForValidTransactions  (optional) (default to false)
/// @param allowPartial  (optional) (default to false)
/// @param transactionControlNumber  (optional) (default to 1)
/// @param ak901  (optional) (default to e)
/// @param ackVersion  (optional) (default to 4010_997)
/// @param includeTransactions  (optional) (default to false)
/// 
///  code:200 message:"Success",
///  code:400 message:"Bad Request",
///  code:500 message:"Server Error"
///
/// @return NSArray<SWGEdiFabricWebApiModelsX12Acknowledgment>*
-(NSURLSessionTask*) acknowledgeX12WithEdiFile: (NSURL*) ediFile
    readMode: (NSString*) readMode
    accept: (NSString*) accept
    charSet: (NSString*) charSet
    continueOnError: (NSNumber*) continueOnError
    skipTrailerValidation: (NSNumber*) skipTrailerValidation
    syntaxSet: (NSString*) syntaxSet
    transactionDuplicate: (NSNumber*) transactionDuplicate
    groupDuplicate: (NSNumber*) groupDuplicate
    technicalAck: (NSString*) technicalAck
    generateForValidTransactions: (NSNumber*) generateForValidTransactions
    allowPartial: (NSNumber*) allowPartial
    transactionControlNumber: (NSNumber*) transactionControlNumber
    ak901: (NSString*) ak901
    ackVersion: (NSString*) ackVersion
    includeTransactions: (NSNumber*) includeTransactions
    completionHandler: (void (^)(NSArray<SWGEdiFabricWebApiModelsX12Acknowledgment>* output, NSError* error)) handler;



@end
