/**
 * EdiFabric API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface EdiFabricCoreModelEdiEdifactS003 { 
    interchangeRecipientIdentification1?: string;
    identificationCodeQualifier2?: string;
    interchangeRecipientInternalIdentification3?: string;
    interchangeRecipientInternalSubIdentification4?: string;
}
