/**
 * EdiFabric API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface EdiFabricCoreModelEdiEdifactS001 { 
    syntaxIdentifier1?: string;
    syntaxVersionNumber2?: string;
    serviceCodeListDirectoryVersionNumber3?: string;
    characterEncoding4?: string;
}
