/**
 * EdiFabric API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface EdiFabricCoreModelEdiErrorContextsDataElementErrorContext { 
    name?: string;
    position?: number;
    code?: EdiFabricCoreModelEdiErrorContextsDataElementErrorContext.CodeEnum;
    value?: string;
    componentPosition?: number;
    repetitionPosition?: number;
    message?: string;
}
export namespace EdiFabricCoreModelEdiErrorContextsDataElementErrorContext {
    export type CodeEnum = 'RequiredDataElementMissing' | 'ConditionalRequiredDataElementMissing' | 'TooManyDataElements' | 'DataElementTooShort' | 'DataElementTooLong' | 'InvalidCharacterInDataElement' | 'InvalidCodeValue' | 'InvalidDate' | 'InvalidTime' | 'ExclusionConditionViolated' | 'TooManyRepetitions' | 'TooManyComponents' | 'TooFewRepetitions';
    export const CodeEnum = {
        RequiredDataElementMissing: 'RequiredDataElementMissing' as CodeEnum,
        ConditionalRequiredDataElementMissing: 'ConditionalRequiredDataElementMissing' as CodeEnum,
        TooManyDataElements: 'TooManyDataElements' as CodeEnum,
        DataElementTooShort: 'DataElementTooShort' as CodeEnum,
        DataElementTooLong: 'DataElementTooLong' as CodeEnum,
        InvalidCharacterInDataElement: 'InvalidCharacterInDataElement' as CodeEnum,
        InvalidCodeValue: 'InvalidCodeValue' as CodeEnum,
        InvalidDate: 'InvalidDate' as CodeEnum,
        InvalidTime: 'InvalidTime' as CodeEnum,
        ExclusionConditionViolated: 'ExclusionConditionViolated' as CodeEnum,
        TooManyRepetitions: 'TooManyRepetitions' as CodeEnum,
        TooManyComponents: 'TooManyComponents' as CodeEnum,
        TooFewRepetitions: 'TooFewRepetitions' as CodeEnum
    };
}
